### ISSUE TITLE
[Bug]: Epic installer initial update failed

### ISSUE THREAD

**Issue by coocoorhin** [IsaacMarovitz/Whisky#101]
### Description

Description

I get the following error when trying to install epic game launcher for the first time
it tries to update it self and couldn't install the updates after downloading them 

<img width="609" alt="Screenshot 2023-06-13 at 12 23 16" src="https://github.com/IsaacMarovitz/Whisky/assets/6900616/bf16dff6-3ced-491c-a881-69b41af5d5f7">

### Steps to reproduce

Install Whisky.dmg
Create bottle
Install epic installer

### Expected behaviour

run

### What version of Whisky are you using?

pre-0.2.3

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by 91leMAC** [comment]
Hey !
How did you install Epic Games because I can't import with whisky .msi file !

**Comment by barone2k** [comment]
@mavethee GTA V need Rockstar Launcher, so if I download it from Heroic I can't run it in Whisky, because Rockstar Launcher in Whisky cannot access Epic Store, and Epic Store won't install because initial update fail.
So, seems that I need to run directly Epic Launcher, that workaround isn't enough for GTA V.

**Comment by RealMimoi** [comment]
How do I get Heroic Games Launcher working on Whisky? I downloaded the launcher (v2.10.0) for windows and it doesn't work.
![Screenshot 2023-11-27 at 6 11 21 PM](https://github.com/Whisky-App/Whisky/assets/152229121/8d68bac4-66d8-45fe-ba1b-dbbeb7e28e8f)

**Comment by mavethee** [comment]
> How do I get Heroic Games Launcher working on Whisky? I downloaded the launcher (v2.10.0) for windows and it doesn't work.

**_Download macOS release of Heroic._**

1. Create bottle named `Heroic` (or whatever) in Whisky, it will be in this location:
`~/Library/Containers/com.isaacmarovitz.Whisky/Bottles/[Certain UUID]` 
it's easy to verify by selecting `Open Drive C:` in created bottle.

2. Install Heroic, either from arm64e Hombrew or their DMG from GitHub:
`brew install --cask heroic`
or
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/
(pick arm64 macOS dmg).

3. Run Heroic, go to Settings > Game Defaults > Wine/CrossOver Version > pick `GPTK Wine (DX11/12 Only) - Wine x.x` (e.g. 7.7 for most recent one).

4. Now setup Wine prefix, which is exactly under Wine/CrossOver Version section,  press folder icon near default path, press `Shift` + `Command` + `G` and paste the path from first step, then press enter to get to the path, then confirm it.

5. Make sure `ESync` is checked, `Show Stats Overlay` is Metal HUD, so it's up to you.

_**There's no MSync option yet iirc.**_

**Comment by KalyWan** [comment]
it`s work for me -SkipBuildPatchPrereq
![image](https://github.com/Whisky-App/Whisky/assets/104131248/f3795c63-d7bc-45fd-8335-0bff01f9e173)

**Comment by mavethee** [comment]
@KalyWan There's no need to tinker that much as Heroic detects and supports Whisky now.
