### ISSUE TITLE
[Bug]: None of the games work, game window/screen never shows, WINE closes after few seconds with the same log messages.

### ISSUE THREAD

**Issue by serista** [IsaacMarovitz/Whisky#106]
### Description

I have tried 3 games: ELDEN RING, Stray, Humanity. None of them worked, after few seconds WINE closes and Whisky's log files are basically the same. Something about resolving host name IP and wineusb.sys.so (attached). Tried 3 different versions of Whisky: 0.2.1, 0.2.3, 0.2.4.

[2023-06-14T08:08:51Z.log](https://github.com/IsaacMarovitz/Whisky/files/11744041/2023-06-14T08.08.51Z.log)
[2023-06-14T08:07:43Z.log](https://github.com/IsaacMarovitz/Whisky/files/11744042/2023-06-14T08.07.43Z.log)
[2023-06-14T08:34:06Z.log](https://github.com/IsaacMarovitz/Whisky/files/11744043/2023-06-14T08.34.06Z.log)
[2023-06-14T08:08:18Z.log](https://github.com/IsaacMarovitz/Whisky/files/11744044/2023-06-14T08.08.18Z.log)

My system is Mac Mini M1, Sonoma beta 1.

### Steps to reproduce

Install Sonoma beta 1, install Whisky 0.2.1/ 0.2.3/ 0.2.4, drag Game_porting_toolkit_beta.dmg to Whisky's window, create Win 10 bottle, copy game folder to C:/Games, run game executable with Run.. command.  

### Expected behaviour

Working games.

### What version of Whisky are you using?

pre-0.2.4

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by aske-cph** [comment]
Same errors and behaviour here with about 10 steam games tried, nothing starts. 

Is it because of some "genuine software check" done by steam that gets blocked somehow?

There's quite a lot of posts both here and on discord with this exact behaviour so it seems to be a very common problem.

**Comment by serista** [comment]
> Is it because of some "genuine software check" done by steam that gets blocked somehow?

I don't know what's going on, but f.e. the same copies of Stray and Humanity both run under CrossOver/Wine on Ventura.

**Comment by IsaacMarovitz** [comment]
@serista Elden Ring at least requires a bypass to get around the anti-cheat. I'm not sure about Stray and Hummanity but if they work in stock GPTK they should work in Whisky

**Comment by Stefidar** [comment]
Nothing works in Whisky anymore, games that used to work until 0.22 don't work anymore, they don't load.

**Comment by serista** [comment]
> Elden Ring at least requires a bypass to get around the anti-cheat. I'm not sure about Stray and Hummanity but if they work in stock GPTK they should work in Whisky

I don't know about stock GPTK, but they work in CrossOver 22.1.1 on Ventura. Also, the logs are all the same in Whiskey for them and Elden Ring too. I'm almost sure it's not the games problem, I'm feeling that if I try other games that reportedly should work fine according to applegamingwiki the result will be the same. Why there is that wineusb error? Maybe it's the certain version of WINE that causing problems or some needed apps/utilities/libraries are somehow absent in the system... 

But just to be sure, how do I use the anti-cheat bypass?

**Comment by serista** [comment]
> any chance this is related to #94 ? seems it

See the Whisky's logs. If #94 generates same errors, it's the same issue.

**Comment by serista** [comment]
Ok, I just renamed copied and renamed eldenring.exe to start_protected_game.exe (supposedly bypassing the anti-cheat) but result is the same:

Launched Wine (712)
002c:err:winediag:getaddrinfo Failed to resolve your host name IP
0068:err:module:open_builtin_so_file failed to load .so lib "/Applications/Whisky.app/Contents/Resources/Libraries/Wine/lib/wine/x86_64-unix/wineusb.sys.so"
0068:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
Process exited with code 0

**Comment by IsaacMarovitz** [comment]
Should be fixed in 0.3.0. If not, please open a new issue
