### ISSUE TITLE
0.2.0 Pre-Release: Windows don't render

### ISSUE THREAD

**Issue by zaptrem** [IsaacMarovitz/Whisky#11]
Currently when loading the Steam installer or builtin applications the icon appears in the dock but nothing renders. When I use the Tile window manager to force the "window" into the center of the screen the following renders about ten pixels tall: 
![image](https://github.com/IsaacMarovitz/Whisky/assets/1612230/17ae8cd2-266b-488f-a295-64410c6cb019)

**Comment by nadiaholmquist** [comment]
Same issue here on a Mac Studio running Sonoma.

Running the bundled WINE from the terminal, it complains that libraries it needs are missing, notably freetype needed for font rendering which is probably why windows don't render. Did you maybe forget to bundle them?

**Comment by pesqair** [comment]
Same here. Macbook Pro M1 Max

**Comment by dewest456** [comment]
I have the same problem. M1 Mac Mini 14.0

**Comment by vladyera** [comment]
yep, same issue, m1 pro macbook

**Comment by zaptrem** [comment]
> I was able to work around this issue on my M1 Max by installing the `game-porting-toolkit` and replacing all of the WINE stuff in Whisky with the ones built with the toolkit.

We solved the issue simultaneously! Wine inside Whisky is likely searching for some lib, not finding it, then searching through the path until it finds the one in `game-porting-toolkit` as installed by homebrew. I didn't need to copy any files other than those described by Whisky's installation instructions. All I did was build the toolkit via homebrew. Ensure `brew doctor` does not complain about messed up Cellar directories or you will have to build subversion from scratch which is currently impossible due to a broken dependency. Copy/pasting the instructions for those who may not have an Apple dev account:

1. Setup your development and Homebrew environment
	•	Ensure the Command Line Tools for Xcode 15 beta are installed. Visit https://developer.apple.com/downloads to download these tools.
	•	Open Terminal.
	•	The Game Porting Toolkit runs under Rosetta 2. Ensure that Rosetta 2 is installed.
softwareupdate --install-rosetta
	•	Enter an x86_64 shell to continue the following steps in a Rosetta environment. All subsequent commands should be run within this shell.
arch -x86_64 zsh
	•	Install the x86_64 version of Homebrew if you don't already have it.
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
	•	Make sure the brew command is on your path:
which brew
		If this command does not print /usr/local/bin/brew, you must either modify your PATH to put /usr/local/bin first, or fully specify the path to brew in the subsequent commands.
	•	Tap the Apple Homebrew tap, which can be found at https://github.com/apple:
brew tap apple/apple http://github.com/apple/homebrew-apple
	•	Install the game-porting-toolkit formula. This formula downloads and compiles several large software projects. How long this takes will depend on the speed of your computer.
brew -v install apple/apple/game-porting-toolkit
	•	If during installation you see an error such as “Error: game-porting-toolkit: unknown or unsupported macOS version: :dunno”, your version of Homebrew doesn’t have macOS Sonoma support. Update to the latest version of Homebrew and try again.
brew update brew -v install apple/apple/game-porting-toolkit

**Comment by nadiaholmquist** [comment]
I think it’s not necessarily the building it yourself that makes the difference, but rather that building it yourself pulls in all the necessary dependencies in homebrew. If you forgot to include them or forgot to adjust rpaths on the WINE binaries, it will try to find them from homebrew’s default install paths.

**Comment by IsaacMarovitz** [comment]
Even after Wine is built it's still looking for stuff on homebrew? That seems unlikely. I uninstalled the toolkit itself from homebrew as soon as I was done building.

**Comment by nadiaholmquist** [comment]
Did it also uninstall dependencies? Try making brew uninstall freetype, that should very obviously break things if this is what is happening.

**Comment by upstroke-version** [comment]
> Interesting that you had to build it yourself to get it working. Does this happen on all non-M1 Macs?

I'm on M1 Mac and have this issue. 
Hope this could be fixed with Whisky update.
Using x86_64 shell and Homebrew with rosetta and compiling lots of projects sounds like a hassle...

**Comment by IsaacMarovitz** [comment]
<img width="1440" alt="Screenshot 2023-06-07 at 13 41 04" src="https://github.com/IsaacMarovitz/Whisky/assets/42140194/e1c01795-643c-4302-b827-37fc1015bc0e">
I completely uninstalled x86 homebrew and it still seems to work on my machine

**Comment by IsaacMarovitz** [comment]
<img width="1010" alt="Screenshot 2023-06-07 at 13 42 15" src="https://github.com/IsaacMarovitz/Whisky/assets/42140194/74ac283f-a759-4f2d-a607-a925377bd642">

Ahh Steam *does* have issues

**Comment by IsaacMarovitz** [comment]
I've added instructions for fixing this issue to the faq channel on the discord.

**Comment by IsaacMarovitz** [comment]
> > I've added instructions for fixing this issue to the faq channel on the discord.
> 
> How can I join discord server? tried clicking the image in the readme and it doesn't work for me.

https://discord.gg/WAgj8arM

**Comment by zaptrem** [comment]
> I've added instructions for fixing this issue to the faq channel on the discord.

Siloing knowledge in Discord makes it impossible to find via search engines. Maybe an FAQ in the readme would be better?

**Comment by IsaacMarovitz** [comment]
> Siloing knowledge in Discord makes it impossible to find via search engines. Maybe an FAQ in the readme would be better?

Added to the readme

**Comment by qcdead** [comment]
If anyone is still having this issue after building the files, you have to create a new bottle in order for it to work.

**Comment by chadlavi** [comment]
I've installed the x86 version of homebrew and installed freetype there, but when I try to run steam I just get 

<img width="705" alt="image" src="https://github.com/IsaacMarovitz/Whisky/assets/7226642/14316619-7957-47a8-b296-a8aeaaa09d83">

Anyone know what's going wrong there?
