### ISSUE TITLE
[Bug]: Genshin Impact Installer doesn't show anything.

### ISSUE THREAD

**Issue by ShikiSuen** [IsaacMarovitz/Whisky#111]
### Description

Genshin Impact Installer doesn't show anything.

### Steps to reproduce

Download the installer, and put it in a newly-created Windows 10 bottle, then run.

The installer is downloaded from Mihoyo's official Chinese website:
- Page: https://ys.mihoyo.com/
- Installer link (as shown in the screenshot below): https://ys-api.mihoyo.com/event/download_porter/link/ys_cn/official/pc_default
<img width="591" alt="image" src="https://github.com/IsaacMarovitz/Whisky/assets/3164826/cb982da5-d177-4a66-944e-c20322da13d1">

### Expected behaviour

The installer shows up.

### Logs

```bash
Whisky Version: pre-0.2.4
Date: 2023年6月15日 星期四 19:46:48
Bottle Name: GenshinImpact
Wine Version: 7.7
Windows Version: win10
Bottle URL: /Users/shikisuen/Library/Containers/com.isaacmarovitz.Whisky/Bottles/GenshinImpact

Arguments: start /unix /Users/shikisuen/Library/Containers/com.isaacmarovitz.Whisky/Bottles/GenshinImpact/drive_c/yuanshen_setup_20230508115935.exe 

Environment:
{
}

Launched Wine (53678)
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
0068:err:module:open_builtin_so_file failed to load .so lib "/Applications/Whisky.app/Contents/Resources/Libraries/Wine/lib/wine/x86_64-unix/wineusb.sys.so"
0068:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
Process exited with code 0
```

### What version of Whisky are you using?

pre-0.2.4

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Patt92** [comment]
you can select open logs folder in the menu bar

**Comment by ShikiSuen** [comment]
@Patt92 Thanks. I updated the log in the main post.

**Comment by IsaacMarovitz** [comment]
<img width="730" alt="Screenshot 2023-06-16 at 21 12 05" src="https://github.com/IsaacMarovitz/Whisky/assets/42140194/8b901d61-fee5-4343-82d7-e7680d7ccfcc">

Fixed in pre-3.0.0

**Comment by ShikiSuen** [comment]
@IsaacMarovitz It appears that you are using a different installer which is unable to login those Genshin accounts registered in Mainland China.

I'll test the Mainland China Genshin client later. Will ping here if it still has issues.

**Comment by ShikiSuen** [comment]
It's working. Case finished.
<img width="811" alt="image" src="https://github.com/IsaacMarovitz/Whisky/assets/3164826/f8d7f845-e0fd-4736-a27a-d2311182be04">
