### ISSUE TITLE
[Feature]: Ability to choose between Game sporting Toolkit and Standard Wine

### ISSUE THREAD

**Issue by JOOT49** [IsaacMarovitz/Whisky#112]
### Is your feature request related to a problem?

On Intel MacBooks running Ventura, whiskey is impossible to run because of the game porting toolkit using apple silicon libraries.

### Describe the solution you'd like

Make it optional to import the game porting toolkit, or make separate builds that do not require it

### Anything else?

Sucks that Intel users can only use heavily outdated versions.

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
Perhaps #110 is what you are asking for?

**Comment by JOOT49** [comment]
> Perhaps #110 is what you are asking for?

Not exactly. In old versions of the app, upon installation it would not prompt you to install the game porting toolkit, and instead would just use wine. I wish for this to still be possible in modern releases of whiskey.

**Comment by IsaacMarovitz** [comment]
Tbh, I'm not sure I'm too bothered about supporting Macs on Ventura. If your on Ventura either use GPTK as you can, or use old Whisky, or stick with CX
