### ISSUE TITLE
[Bug]: BeamNG.Drive - Video card not supported

### ISSUE THREAD

**Issue by richstokes** [IsaacMarovitz/Whisky#118]
### Description

![image](https://github.com/IsaacMarovitz/Whisky/assets/13403491/58dd5b98-f135-42e6-a09c-d079120057dc)

### Steps to reproduce

Open the game via Steam

### Expected behaviour

The game should start / whisky should have the latest DX version, I guess?

### Logs

```bash
N/A
```

### What version of Whisky are you using?

pre-0.3.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by richstokes** [comment]
FWIW, I get a similar error when opening UnrealRacing:
![image](https://github.com/IsaacMarovitz/Whisky/assets/13403491/2bbf0f60-f57e-4cd3-9fb9-4e8c8ff1821f)


its like Whisky/GPT is not exposing DX/the video card correctly

**Comment by aske-cph** [comment]
Same. With Witcher 3 on Sonoma. Says theres no directx11 support, so seems like dx11 is missing somehow?

**Comment by richstokes** [comment]
I actually can't get *any* games to start - they flash open for a second and then get killed. But at least the above shows an error.

**Comment by troll1120** [comment]
me too

**Comment by IsaacMarovitz** [comment]
Duplicate, see #124
