### ISSUE TITLE
[Feature Request]: Controller Support

### ISSUE THREAD

**Issue by MCChristor** [IsaacMarovitz/Whisky#12]
Controller Support pls

**Comment by badwished** [comment]
put with-sdl2. in the Arguments config.    playing diablo 4 with controller

**Comment by ohaiibuzzle** [comment]
> put with-sdl2. in the Arguments config. playing diablo 4 with controller

Lemme just hit you with this: That actually does nothing
The compilation process for Wine, unless you explicitly use a "without" flag, will just look for what is available and automatically build those features in.
The "with" flags is simply there to ensure that the build will fail if libraries aren't found

**Comment by dirkgroot** [comment]
I've played Dark Souls: REMASTERED and NieR:Automata via Steam using Whisky, and my DualShock contoller works in both cases. Steam does not seem to detect the controller, however.

**Comment by ohaiibuzzle** [comment]
> I've played Dark Souls: REMASTERED and NieR:Automata via Steam using Whisky, and my DualShock contoller works in both cases. Steam does not seem to detect the controller, however.

That's normal actually. I think statistically for GPTk right now, DualShock/DualSense controllers seems to work better than Xbox controller... for some reason.
Xbox controllers seems to be more on the side of "it works sometimes"

**Comment by kylejericson** [comment]
Do you have to do anything special to get the controller to work in this? I teest with a Steam game and it doesn't detect my Xbox One bluetooth controller. The Mac can see it, but Whisky/Steam doesn't see it.

**Comment by craigcampbell** [comment]
I'm not sure if I'm adding anything to this convo but I'm unable to get neither dual shock 2 nor a cabled xbox controller to work. Whiskey says "using steam-translate' and shows the graphics on how hit'd translate from xbox to dual sense in the steam ui, but when i launch elden ring no input comes across.

**Comment by punk1503** [comment]
I have similar issues with dualsense controller. However steam fully recognizes it, but the game only shows me pc controls and does nothing when I press buttons on gamepad.
