### ISSUE TITLE
[Bug]: 'GPU Driver' Problems - Tracking Issue

### ISSUE THREAD

**Issue by IsaacMarovitz** [IsaacMarovitz/Whisky#124]
The GPTK installer isn't working as intended. As a result, Wine is unable to find D3DM DLLs, causing programs that require graphics to fail.

`Assertion failed: (GFXTHandle && "Failed to dlopen D3DMetal"), function D3DRMDispatch_Init_block_invoke, file shared.mm, line 694`

The error lists a function on `libd3dshared.dylib` which is part of GPTK. It seems it is not finding the `D3DMetal.dylib` correctly possibly because the search path is `@rpath/D3DMetal.framework/D3DMetal` and `libd3dshared.dylib` doesn’t have any `LC_RPATH` load commands. Not sure what happens in that scenario.

**Comment by alexsch01** [comment]
https://www.reddit.com/r/macgaming/comments/14bltwc/gpt_whiskey_how_to_fix_no_gpu_found_error/

**Comment by IsaacMarovitz** [comment]
> https://www.reddit.com/r/macgaming/comments/14bltwc/gpt_whiskey_how_to_fix_no_gpu_found_error/

This is confusing, the process described in this Reddit post is the exact same process Whisky does automatically

**Comment by IsaacMarovitz** [comment]
> https://www.reddit.com/r/macgaming/comments/14bltwc/gpt_whiskey_how_to_fix_no_gpu_found_error/

This is confusing, the process described in this Reddit post is the exact same process Whisky does automatically

**Comment by IsaacMarovitz** [comment]
> https://www.reddit.com/r/macgaming/comments/14bltwc/gpt_whiskey_how_to_fix_no_gpu_found_error/

This is confusing, the process described in this Reddit post is the exact same process Whisky does automatically

**Comment by IsaacMarovitz** [comment]
> https://www.reddit.com/r/macgaming/comments/14bltwc/gpt_whiskey_how_to_fix_no_gpu_found_error/

This is confusing, the process described in this Reddit post is the exact same process Whisky does automatically

**Comment by richstokes** [comment]
I don't even have a `/Contents/Resources/Libraries` folder in my Whisky.app 🤔 there is a `Libraries.tar.gz` tho

**Comment by aske-cph** [comment]
Also only a libraries.tar.gz here. Expanding that file and it still doesn't work unfortunately.

**Comment by richstokes** [comment]
Looks like the actual folder is `/Users/$USERNAME/Library/Application\ Support/Whisky/Libraries/Wine/lib`, but that seems OK to me

**Comment by ohaiibuzzle** [comment]
For impatient folks who can't wait for a fix, here is a temp fix

First, open Finder, press `Cmd` + `Shift` + `G` and go to `~/Library/Application Support/` and delete the Whisky folder (don't worry this won't kill your bottles)

Next, fire up Whisky, let it shows the GPTK install popup but **DO NOT** drag a dmg into it. Force Whisky to quit

Run this in your Terminal, make sure you have the GPTK dmg mounted
`curl -o- "https://gist.githubusercontent.com/ohaiibuzzle/71a0bff04956af7540156a30896e4bfd/raw/af438664138a03baf6edc7647dcc09d84fbe432c/fixmywhisky.sh?bustthecache=1" | bash` 

Open Whisky and cross your fingers that D3D works

**Comment by richstokes** [comment]
Didn't work for me / got these errors:
```
curl -o- "https://gist.githubusercontent.com/ohaiibuzzle/71a0bff04956af7540156a30896e4bfd/raw/af438664138a03baf6edc7647dcc09d84fbe432c/fixmywhisky.sh?bustthecache=1" | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   881  100   881    0     0   9713      0 --:--:-- --:--:-- --:--:-- 10488
Please make sure GPTK dmg is mounted
ditto: /Users/rich/Library/Application Support/Whisky/Libraries/Wine/lib/external/D3DMetal.framework/Versions/Current: Is a directory
cp: external/D3DMetal.framework/D3DMetal: No such file or directory
cp: cannot overwrite directory ./D3DMetal.framework/Resources with non-directory external/D3DMetal.framework/Resources
cp: external/D3DMetal.framework/Headers: No such file or directory
xattr: No such file: external/D3DMetal.framework/Headers
```

**Comment by ohaiibuzzle** [comment]
> Didn't work for me / got these errors:
> 
> ```
> curl -o- "https://gist.githubusercontent.com/ohaiibuzzle/71a0bff04956af7540156a30896e4bfd/raw/af438664138a03baf6edc7647dcc09d84fbe432c/fixmywhisky.sh?bustthecache=1" | bash
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   881  100   881    0     0   9713      0 --:--:-- --:--:-- --:--:-- 10488
> Please make sure GPTK dmg is mounted
> ditto: /Users/rich/Library/Application Support/Whisky/Libraries/Wine/lib/external/D3DMetal.framework/Versions/Current: Is a directory
> cp: external/D3DMetal.framework/D3DMetal: No such file or directory
> cp: cannot overwrite directory ./D3DMetal.framework/Resources with non-directory external/D3DMetal.framework/Resources
> cp: external/D3DMetal.framework/Headers: No such file or directory
> xattr: No such file: external/D3DMetal.framework/Headers
> ```

That's OK. Ignore all of those errors. I am just too lazy to void stderr

**Comment by richstokes** [comment]
Fair enough, games still dont launch though 🙃

**Comment by ohaiibuzzle** [comment]
If they don't, reboot your Mac. that will ensure that all stray Wine processes are killed

**Comment by richstokes** [comment]
Still no luck after a reboot 🤔

**Comment by ohaiibuzzle** [comment]
> Still no luck after a reboot 🤔

Try doing it again, I edited the command to bulletproof it a bit
Make sure that you did not feed a GPTK dmg to Whisky. The script will fail if you do

**Comment by richstokes** [comment]
No luck -- same thing, steam opens fine but games just instantly die

**Comment by dbeistel** [comment]
I followed along, and Now I am getting an error that wine64 doesn't exist.   I am going to try again to see if I missed a step.

**Comment by IsaacMarovitz** [comment]
Fixed in 0.3.1

**Comment by richstokes** [comment]
Not sure what I'm doing wrong, updated to 0.3.1, gave it the GPT .dmg when prompted. Again steam is loading but games insta-crash

**Comment by IsaacMarovitz** [comment]
> Not sure what I'm doing wrong, updated to 0.3.1, gave it the GPT .dmg when prompted. Again steam is loading but games insta-crash

Probably an issue with that specific game

**Comment by richstokes** [comment]
I've tried 5 or 6 different games, none of them work

**Comment by IsaacMarovitz** [comment]
> I've tried 5 or 6 different games, none of them work

Can you list them

**Comment by richstokes** [comment]
Quake 3 Arena
Sonic Mania
BeamNG.Drive
Toxikk
Deathmatch Classic

**Comment by IsaacMarovitz** [comment]
Quake 3 Arena is a DX3 game
Sonic Mania is a DX9 game

both of those are likely a wash yeah/

BeamNG.Drive is DX11 so that should work

Toxikk I have no idea what DX version it's using but it's ancient and same with Deatmatch Classic.

Whisky works best with DirectX 12 titles.

**Comment by delaz** [comment]
> com

I dont get error msg after that. But the diablo 4 crashed without any msg...

**Comment by RussianLioN** [comment]
I still have the error: "No GPUs found! A GPU is required to play Diablo IV. This might occur if you are currently installing GPU drivers" with GPTK after update GPTK to 1.0.2

**Comment by kode54** [comment]
You need to delete that `~/Library/Application Support/Whisky` folder and reinstall the .dmg by dragging it onto Whisky on startup. The fix doesn't seem to automate this.

**Comment by RussianLioN** [comment]
> You need to delete that `~/Library/Application Support/Whisky` folder and reinstall the .dmg by dragging it onto Whisky on startup. The fix doesn't seem to automate this.

I did, but it didn’t help
The solution that worked for me was:
Compete wipes GPTK & Whiskey with installed games, then reinstall GPTK и Games, but without Whiskey

**Comment by shadzik** [comment]
Same problem here with Diablo 4:

Updated from Whisky 0.3.1 to 1.0.0, GPT from beta to 1.0.2 beta and Diablo claims I have no graphics card.

Removing `~/Library/Application Support/Whisky` didn't help
