### ISSUE TITLE
[Feature]: Add Setting for retina resolution

### ISSUE THREAD

**Issue by blueagler** [IsaacMarovitz/Whisky#126]
### Is your feature request related to a problem?

The UI is very unclear in default

### Describe the solution you'd like

I know how to do it:

1. Add registry entry for retina support:

Add the following key or change the existing key (CURRENT_USER, not SOFTWARE):
[HKEY_CURRENT_USER\Software\Wine\Mac Driver]
"RetinaMode" = "y"

<img width="1800" alt="Screenshot 2023-06-18 at 2 28 06 AM" src="https://github.com/IsaacMarovitz/Whisky/assets/61572188/d196d37b-a975-4a4f-a174-b2b73def76b0">

2. Change DPI settings in Wine Config

Under Graphics, set DPI to 254 for Macbook 14 Pro

<img width="1800" alt="Screenshot 2023-06-18 at 2 27 29 AM" src="https://github.com/IsaacMarovitz/Whisky/assets/61572188/6169eb7a-bbde-42cf-93d9-b1510123f0e9">

Preview:
<img width="1800" alt="Screenshot 2023-06-18 at 2 24 13 AM" src="https://github.com/IsaacMarovitz/Whisky/assets/61572188/a4b72824-d9be-429a-8559-7acf3238666c">

### Anything else?

Maybe you could add 

a toggle that enables retina

and 

a input that sets DPI

for those who does not know how to change those configs

### Issue Language

- [X] Yes my issue is written in English

**Comment by blueagler** [comment]
it seems like Hogwards will crash in Retina, but Diablo 4 is fine

**Comment by Pantoria** [comment]
I do not see the mac driver at the same position

**Comment by blueagler** [comment]
> I do not see the mac driver at the same position

If it is not existed, you need to create it by yourself.

**Comment by ohaiibuzzle** [comment]
#132

**Comment by IsaacMarovitz** [comment]
Merged

**Comment by JamIsJam88** [comment]
I'm running a Mac Studio. What DPI should I set the wine graphics to?
