### ISSUE TITLE
[Feature] Release a brew package

### ISSUE THREAD

**Issue by wujekbogdan** [IsaacMarovitz/Whisky#134]
### Is your feature request related to a problem?

I can't install Whisky with `brew install whisky`

### Describe the solution you'd like

[Create a brew formula](https://docs.brew.sh/Adding-Software-to-Homebrew) and add it to the registry

### Anything else?

I think this can be automated thanks to [`bump-homebrew-formula` Github Action](https://github.com/marketplace/actions/bump-homebrew-formula)

### Issue Language

- [X] Yes my issue is written in English

**Comment by benwaco** [comment]
not possible to add to the official brew repo right now, see #51

**Comment by IsaacMarovitz** [comment]
We can make our own cask

**Comment by IsaacMarovitz** [comment]
Working on one https://github.com/IsaacMarovitz/homebrew-whisky/pull/1

**Comment by airsquared** [comment]
You don't need signing or notarization to be added to Homebrew. I have an application on Homebrew Cask without any signing/notarization, I just request my users to install with `brew install --no-quarantine [cask]`.

**Comment by IsaacMarovitz** [comment]
> You don't need signing or notarization to be added to Homebrew. I have an application on Homebrew Cask without any signing/notarization, I just request my users to install with `brew install --no-quarantine [cask]`.

The plan is to get on the official homebrew tap

**Comment by airsquared** [comment]
Yes, my unsigned application is on the official Homebrew Cask tap. But it seems you got the signing/notarization handled now, so it doesn't matter.

**Comment by IsaacMarovitz** [comment]
Released
