### ISSUE TITLE
[Bug]: No Programs on Bottle

### ISSUE THREAD

**Issue by blisstik** [IsaacMarovitz/Whisky#139]
### Description

Hello - on a fresh install of Sonoma beta, I downloaded Whisky 0.3.1, dragged the DMG file, proceeded to create a Bottle that would not pop-up on left side until I close the window (not the app).

Go back to the app, it will show up but there are no programs or can't open Wine Config.

### Steps to reproduce

See above

### Expected behaviour

Should be able to open Wine config, etc.

### Logs

```bash
None
```

### What version of Whisky are you using?

pre-0.3.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by timrsnbckr** [comment]
Did you install Rosetta 2 before?
