### ISSUE TITLE
Error: You can’t use this version of the application “Whisky” with this version of macOS.

### ISSUE THREAD

**Issue by Niek** [IsaacMarovitz/Whisky#14]
I'm getting this error:

<img width="372" alt="Screenshot 2023-06-07 at 09 38 15" src="https://github.com/IsaacMarovitz/Whisky/assets/213140/62aebe2f-6705-4c02-8678-b44946f07131">

macOS version: `13.4 (22F66)`
Whisky version: `pre-0.2.0`

Does this require a beta version of macOS?

**Comment by MCChristor** [comment]
Yes, macOS 14.0 is required

**Comment by Niek** [comment]
My bad - works great in macOS 14 beta.

**Comment by vesper8** [comment]
We now have confirmation that this can all work on Ventura : )

https://www.reddit.com/r/macgaming/comments/143ae4f/diablo_iv_on_m1_max_mbp_14_using_macos_ventura_134/
