### ISSUE TITLE
[Bug]: Duplicate exe shortcuts

### ISSUE THREAD

**Issue by ArmasF31** [IsaacMarovitz/Whisky#149]
### Description

<img width="1130" alt="image" src="https://github.com/IsaacMarovitz/Whisky/assets/66262484/6beb1e9f-ff90-4d84-bc1b-7c7a55174738">

As you can see in the picture, there are some duplicate programs detected. They have the exact same path in the details, so I'm not sure what causes it.

### Steps to reproduce

Install a program, doesn't happen with every program tho.

### Expected behaviour

Show each exe once. Maybe include an option to delete/add programs by the user if that is easier than fixing the duplicates.

### Logs

```bash
Bottle is not running yet.
```

### What version of Whisky are you using?

pre-0.3.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Fix coming in next release
