### ISSUE TITLE
[Bug]: Fallout 4 Windowing Issues

### ISSUE THREAD

**Issue by ArmasF31** [IsaacMarovitz/Whisky#151]
### Description

This is more just to see if other people run into the same issue as me, if they do it might be a problem with gpt or whisky. Would be awesome to get it fixed tho, since it runs really well (not just in the menu) and still is a great game.

<img width="1277" alt="image" src="https://github.com/IsaacMarovitz/Whisky/assets/66262484/279c2164-5f01-4e6e-a407-50465d568e47">

### Steps to reproduce

Install game and run it

### Expected behaviour

Mouse movement should be work in game as well, it works fine in the menu wich is odd I think

### Logs

```bash
Unable to capture
```

### What version of Whisky are you using?

pre-0.3.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
<img width="522" alt="image" src="https://github.com/IsaacMarovitz/Whisky/assets/23693150/2bc56b6a-7c5d-44f3-8330-31163fb08473">

Perhaps this option here?

**Comment by ArmasF31** [comment]
<img width="1277" alt="image" src="https://github.com/IsaacMarovitz/Whisky/assets/66262484/d5fda559-8bdd-4bc3-ac9e-53cf2afaf1fb">
Mouse is still captured and doesn't move like it should. It doesn't even cover the whole window before it get stopped, so maybe its a resolution/scaling issue.

**Comment by vladashram** [comment]
Where did you source your non-Steam copy of Fallout 4?

**Comment by IsaacMarovitz** [comment]
I'm not going to support a game from a cracked source. Is this same issue present on the Steam version of Fallout 4?

**Comment by palsch** [comment]
Maybe this can help: https://www.applegamingwiki.com/wiki/Fallout_4#Mouse_locked_to_screen

**Comment by IsaacMarovitz** [comment]
Thats probably the solution yeah
