### ISSUE TITLE
[Bug]: preloader: Warning: failed to reserve range 0000000000010000-0000000000110000

### ISSUE THREAD

**Issue by anatblsv** [IsaacMarovitz/Whisky#156]
### Description

Hello all! Can you help me with this issue?

After starting game (Resident Evil 2 Remake) I see intro and message about savign process, and when I click "OK" or just wait few times opens second window in Dock of "preloader" and game freezing. I killing processes and opens logs.

Error in the log - preloader: Warning: failed to reserve range 0000000000010000-0000000000110000

I trying change wine files from other sources (gcenx crossover fix, wine 8.1 build and other), just replace files and test it. After replacing game not started. Now i reinstall Whiskey and try again - ang get same error. Help me pls. I read info about mac os 13.4 have difference with using ram, but i dont know how to fix it. 

### Steps to reproduce

After starting game (Resident Evil 2 Remake) I see intro and message about savign process, and when I click "OK" or just wait few times opens second window in Dock of "preloader" and game freezing.

### Expected behaviour

Game not working, error in the log - preloader: Warning: failed to reserve range 0000000000010000-0000000000110000

### Logs

```bash
Whisky Version: pre-0.3.1
Date: 23.06.2023, 11:17:42
macOS Version: Версия 13.4 (Выпуск 22F66)
Bottle Name: RE2
Wine Version: 7.7
Windows Version: win10
Bottle URL: /Users/anatoliy/Library/Containers/com.isaacmarovitz.Whisky/Bottles/RE2

Arguments: start /unix /Users/anatoliy/Library/Containers/com.isaacmarovitz.Whisky/Bottles/RE2/drive_c/Program Files/RESIDENT EVIL 2/re2.exe 

Launched Wine (71395)
0100: thread_get_state failed on Apple Silicon - faking zero debug registers
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
Process exited with code 0
```

### What version of Whisky are you using?

pre-0.3.1

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by anatblsv** [comment]
Whiskey on Mac os 13.4 works normally for all? Only me have this issue?

**Comment by wesley-maney** [comment]
Nope, same issue here on Ventura (13.4.1) with an M1 Max. None of the exe's (different games, different engines, different eras, installers and portable) I try open - they all fail with this exact error.

I have tried reinstalling Whisky (0.3.1) and remove the bottle, but that doesn't make a difference. Whisky 0.3 and before also don't work because they used to have the "Wine 32 bit" error.

Sample log:
`Whisky Version: pre-0.3.1
Date: 29/6/2023, 15:40:32
macOS Version: Version 13.4.1 (Build 22F82)
Bottle Name: Test
Wine Version: 7.7
Windows Version: win10
Bottle URL: /Users/username/Library/Containers/com.isaacmarovitz.Whisky/Bottles/Test

Arguments: start /unix /Users/username/Library/Application Support/CrossOver/Bottles/Test/drive_c/users/crossover/Test/Game.exe 

Launched Wine (15585)
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
Process exited with code 0`

**Comment by anatblsv** [comment]
> Nope, same issue here on Ventura (13.4.1) with an M1 Max. None of the exe's (different games, different engines, different eras, installers and portable) I try open - they all fail with this exact error.
> 
> I have tried reinstalling Whisky (0.3.1) and remove the bottle, but that doesn't make a difference. Whisky 0.3 and before also don't work because they used to have the "Wine 32 bit" error.
> 
> Sample log:
> 
> ```
> Whisky Version: pre-0.3.1
> Date: 29/6/2023, 15:40:32
> macOS Version: Version 13.4.1 (Build 22F82)
> Bottle Name: Test
> Wine Version: 7.7
> Windows Version: win10
> Bottle URL: /Users/username/Library/Containers/com.isaacmarovitz.Whisky/Bottles/Test
> 
> Arguments: start /unix /Users/username/Library/Application Support/CrossOver/Bottles/Test/drive_c/users/crossover/Test/Game.exe 
> 
> Launched Wine (15585)
> preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
> Process exited with code 0
> ```

Thanks for feedback. I tried reinstall Whiskey too. Also Tried replace libraries from Gcenx https://github.com/Gcenx/CrossOver-fixes, also tried used new wine 8.1 libs, but bottle not work without any errors (just not start)

**Comment by benwaco** [comment]
Ventura is not officially supported by Whisky, it is meant to be ran on Sonoma.

**Comment by IsaacMarovitz** [comment]
`preloader: Warning: failed to reserve range 0000000000010000-0000000000110000` is a warning not an error, it can be ignored. And ditto what ben said
