### ISSUE TITLE
[Bug]: Failed to open program!

### ISSUE THREAD

**Issue by Awesomepieman69** [IsaacMarovitz/Whisky#157]
### Description

Failed to open program!
Failed to open
UbisoftConnectInstaller.exe: The operation couldn't be completed.
(Swift. String error 1.)

### Steps to reproduce

need help 

### Expected behaviour

<img width="248" alt="Screenshot 2023-06-21 at 7 04 32 PM" src="https://github.com/IsaacMarovitz/Whisky/assets/115571387/5bfa3f3d-7ec0-4c2c-bbee-9b7e576423b6">

### Logs

```bash
need help
```

### What version of Whisky are you using?

pre-0.3.1

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ArmasF31** [comment]
Try resetting the bottle (Cmd Shift K) or the whole program. That fixed that error message for me and I have not had it since.
