### ISSUE TITLE
Is it usable on Ventura with Command Line Tools for Xcode 15 beta ?

### ISSUE THREAD

**Issue by vesper8** [IsaacMarovitz/Whisky#16]
I read in the macgaming sub that it's possible to use the porting kit on Ventura if you install the latest beta of the command line tools.

I just did that but when I tried to start Whisky it said my Mac version isn't supported. Is it possible that this can be made to work and the warning is a false positive?

**Comment by Jepl4r** [comment]
It requires MacOS Sonoma, it will not work in Ventura

**Comment by vesper8** [comment]
We now have confirmation that this can all work on Ventura : )

https://www.reddit.com/r/macgaming/comments/143ae4f/diablo_iv_on_m1_max_mbp_14_using_macos_ventura_134/
