### ISSUE TITLE
[Bug]: Obscured buttons offering different functionality than expected, doubled page contents and scrollbar

### ISSUE THREAD

**Issue by kittywhiskers** [IsaacMarovitz/Whisky#165]
### Description

This issue covers two minor UI bugs and one UX bug

UI bugs:
* Doubling of icon on the top bar
* Doubling of page contents after selecting an application (the copy comes with a extra scrollbar)

UX bug:
* At the default size, the "Show in Finder" and "Run" buttons are obscured by the fixed "Open C Drive" and "Run" icons and are only visible when scrolled down

### Steps to reproduce

* Open Whiskey
* Create a bottle and install a package or two, just to populate the Programs bar at the top
  
  ![New Bottle with FurMark and Steam installed](https://github.com/IsaacMarovitz/Whisky/assets/63189531/e766c567-3024-4804-90f4-178edc369a13)

* Double click a program (in this case, `Steam`)
  
  ![Double dialogues](https://github.com/IsaacMarovitz/Whisky/assets/63189531/1fc873c2-5002-472b-9c22-b9f9f83cf037)

* Notice the doubling of the page's contents
  * See the second instance with a scrollbar

* Resize window to original size

  ![Resize window to original size](https://github.com/IsaacMarovitz/Whisky/assets/63189531/468817f7-9133-4ad5-931b-d57157ea7760)

* Notice the obscuring of buttons and the easily confusable similarity between "Run" in the parent window and "Run" in the child window 

* Scroll down to find the actual button you're looking for, then scroll all the way to the bottom

  ![Resized window, scrolled down](https://github.com/IsaacMarovitz/Whisky/assets/63189531/0439b90a-73ef-4db0-9402-68f4ffb7df8b)

* Notice the double bars on the right side

* Notice that throughout the entire experience, the application icon is doubled

### Expected behaviour

* Open Whiskey
* Create a bottle and install a package or two, just to populate the Programs bar at the top
* Select a program
* Have "Open C Drive" and "Run" (any program) replaced with "Show in Finder" and "Run" (selected program) so that when I click "Run", it tries to run the program I explicitly selected

### Logs

```bash
N/A
```

### What version of Whisky are you using?

pre-0.3.1

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
This is incredibly weird, but I am unable to recreate locally on latest master
