### ISSUE TITLE
[Feature]: Shortcuts for applications installed inside bottles 

### ISSUE THREAD

**Issue by aayork** [IsaacMarovitz/Whisky#169]
### Is your feature request related to a problem?

Not related to a problem

### Describe the solution you'd like

Crossover has a feature that allows applications installed into bottles to have shortcuts, is it possible to do something like this with whisky?

### Anything else?

N/A

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Already added in next release

**Comment by mtariqsajid** [comment]
> Already added in next release

how to create a shortcut can you please add in docs

**Comment by neaumusic** [comment]
I have a CLI version set up from [this wiki](https://www.applegamingwiki.com/wiki/Game_Porting_Toolkit) with homebrew (which is where apple computers was founded) with the `/usr/local/bin/brew` version (not `/opt/homebrew/bin/brew`) and `arch -x86_64 zsh` terminal shell, you can make shortcut like this:
```
#!/bin/bash

# Copy the password to the clipboard
echo 'your-password-here' | pbcopy

eval "$(/usr/local/bin/brew shellenv)"; \
arch -x86_64 gameportingtoolkit-no-hud \
~/Library/Containers/com.isaacmarovitz.Whisky/Bottles/73B80174-C1BB-4B07-ACA0-8A032F92A0EC \
'C:\Program Files\IRONMACE\Blacksmith\BlacksmithBootstrap.exe' &

exit 0
```
There might be identical 'game porting toolkit' executables that you find use within ~/Library and /Library [Whisky folders](https://www.reddit.com/r/macgaming/comments/143idco/comment/jnjjrhi/?utm_source=share&utm_medium=web2x&context=3) for the same purpose, but just make a Folder.app with a text file that has that script and make it executable so you can open it `chmod +x /Applications/Dark\ and\ Darker.app`

**Comment by mtariqsajid** [comment]
> @mtariqsajid
> 
> I have a CLI version set up from [this wiki](https://www.applegamingwiki.com/wiki/Game_Porting_Toolkit) with homebrew (which is where apple computers was founded) with the `/usr/local/bin/brew` version (not `/opt/homebrew/bin/brew`) and `arch -x86_64 zsh` terminal shell, you can turn a text file into a shortcut like this:
> 
> ```
> #!/bin/bash
> 
> # Copy the password to the clipboard
> echo 'your-password-here' | pbcopy
> 
> eval "$(/usr/local/bin/brew shellenv)"; \
> arch -x86_64 gameportingtoolkit-no-hud \
> ~/Library/Containers/com.isaacmarovitz.Whisky/Bottles/73B80174-C1BB-4B07-ACA0-8A032F92A0EC \
> 'C:\Program Files\IRONMACE\Blacksmith\BlacksmithBootstrap.exe' &
> 
> exit 0
> ```
> 
> There might be identical 'game porting toolkit' executables that you find to use within ~/Library and /Library [Whisky folders](https://www.reddit.com/r/macgaming/comments/143idco/comment/jnjjrhi/?utm_source=share&utm_medium=web2x&context=3) for the same purpose, but just make a Folder.app with a text file that has that script and [make it executable](https://apple.stackexchange.com/a/269045/82064) so you can open it (not sure which chmod I originally used but something like this `chmod +x /Applications/Dark\ and\ Darker.app/Dark\ and\ Darker`)
> 
> In this case I need my password to paste into the launcher every time, so I use pbcopy, probably not the most secure method of doing that but I don't really mind
> 
> I usually use Kapeli Dash snippets and Control+R on the command-line to recall past commands, but its nice to use spotlight to search for app thing. My terminal is still my favorite fullscreen background though, haha


it required gameportingtoolkit right ? i am on macos 13.5.1 ventura.
