### ISSUE TITLE
Does this actually require Sonoma?

### ISSUE THREAD

**Issue by johnclearyconsulting** [IsaacMarovitz/Whisky#17]
Hi there. It seems that the Porting Toolkit can run on Ventura. Does your tool require Sonoma? Thanks!

**Comment by IsaacMarovitz** [comment]
Yes it does require Sonoma

**Comment by bbsody** [comment]
I installed the Command Line Tools for Xcode 15 beta on macOS Ventura and then compiled the app to run on the system. I have yet to test any game, but I could run the app itself and the Battle.net installer. Unfortunately, I couldn't figure out how to change the Windows build version in order to run Diablo IV.

**Comment by vesper8** [comment]
> I installed the Command Line Tools for Xcode 15 beta on macOS Ventura and then compiled the app to run on the system. I have yet to test any game, but I could run the app itself and the Battle.net installer. Unfortunately, I couldn't figure out how to change the Windows build version in order to run Diablo IV.

I also am trying to get it to run on Ventura, there are mixed reports but no solid confirmation that it can be made to work. I can't update my Mac to a beta version so this is my only way for now.

I followed all the instructions, created the prefix, and tried running several .exe, every time it just does nothing, no error and nothing starts.

Do you get any kind of feedback whenever you try to run an exe?

**Comment by bbsody** [comment]
> Do you get any kind of feedback whenever you try to run an exe?

@vesper8, the only feedback I get is that the app appears on the desktop (and its icon in the Dock).
Did you install the game-porting-toolkit formula via brew?

**Comment by bbsody** [comment]
@vesper8 ah, I never created the prefix. The only things I did to run the Whisky app were:

1. Entering a Rosetta environment with `arch -x86_64 zsh`
2. Installing brew in the environment: `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`
3. ` brew tap apple/apple http://github.com/apple/homebrew-apple`
4. ` brew -v install apple/apple/game-porting-toolkit`.

Then I compiled the app for Ventura, launched it, created a new bottle with Windows 10, hit the "Run" button in the bottom right corner and selected an exe.

**Comment by vesper8** [comment]
I was able to run Stray now, and we now have confirmation that this can all work on Ventura : )

https://www.reddit.com/r/macgaming/comments/143ae4f/diablo_iv_on_m1_max_mbp_14_using_macos_ventura_134/

@IsaacMarovitz sorry for spamming you, but now that it's confirmed that the toolkit CAN work on Ventura. Is there any chance you could modify Whisky to allow it to run on Ventura as well (if the warning was originating from your side)

**Comment by woj-tek** [comment]
^^ would be awesome to get it working on Ventura as well (could we re-open this issue for at least tracking the possibility?)
