### ISSUE TITLE
[Bug]: D2R Game launches but screen is black/doesn't play

### ISSUE THREAD

**Issue by javinladish** [IsaacMarovitz/Whisky#170]
### Description

I am trying to get Diablo II: Resurrection working with Whisky on Ventura 13.4.1.

I was able to install Battle.net, run it, and install D2R.

When I launch the D2R game, it opens but the screen is black with no graphics or sound.

Thanks in advance to anyone who can help!

### Steps to reproduce

- Install Battle.net
- Install D2R
- Try to run D2R

### Expected behaviour

- The game should be playable

### Logs

```bash
I don't know where the logs are stored from Whisky.
```

### What version of Whisky are you using?

pre-0.3.1

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by javinladish** [comment]
Edit: I got it to work! The trick was turning on ESync in the config.

**Comment by javinladish** [comment]
Edit: I got it to work! The trick was turning on ESync in the config.

**Comment by di3tc0ke** [comment]
> How do you turn on ESync? I don't see the option in the bottle configs. Edit: I only have MSync, but turning it on/off doesn't fix anything, I still get a black screen and the game won't start.

I re-installed 2.0.x and worked.

And I found 2.1.3 got ESync option back, but have not tried D2R yet.

Or below helps:
https://github.com/orgs/Whisky-App/discussions/506

**Comment by DmytroKondrashov** [comment]
I am experiencing the same issue with Whisky Version 2.0.2 (28), Sonoma 14.0 (23A344), even with ESync enabled. 

Please help!

**Comment by di3tc0ke** [comment]
> I am experiencing the same issue with Whisky Version 2.2.0, Sonoma 14.0 (23A344), even with ESync enabled.
> 
> Please help!

I have no issues with 2.2.0 + Sonoma 14.1.1. I bought M3 and M3 and M1 both work well. Try uninstall and re-install?

**Comment by DmytroKondrashov** [comment]
> > I am experiencing the same issue with Whisky Version 2.2.0, Sonoma 14.0 (23A344), even with ESync enabled.
> > Please help!
> 
> I have no issues with 2.2.0 + Sonoma 14.1.1. I bought M3 and M3 and M1 both work well. Try uninstall and re-install?

I have updated Sonoma to Sonoma 14.1.1. and Whisky 2.2.0, reinstalled D2R, but the problem remains. Below are my Bottle settings. Maybe I'm doing something wrong?
<img width="757" alt="image" src="https://github.com/Whisky-App/Whisky/assets/61388150/82ac51cd-9c47-42f8-818c-b2255d0f8cf5">

**Comment by di3tc0ke** [comment]
> even with ESync enabled.

But you haven't. You chose MSync.

**Comment by DmytroKondrashov** [comment]
> > even with ESync enabled.
> 
> But you haven't. You chose MSync.

I did, but the result was just an error
<img width="758" alt="image" src="https://github.com/Whisky-App/Whisky/assets/61388150/a3892e3c-de2d-4952-8f0a-ad17741a50bc">
<img width="721" alt="image" src="https://github.com/Whisky-App/Whisky/assets/61388150/6b937015-6464-4d62-baac-453e6be00958">

**Comment by DmytroKondrashov** [comment]
I have found a solution to my specific case. One need to simply disable DXVK

**Comment by di3tc0ke** [comment]
> I have found a solution to my specific case. One need to simply disable DXVK

Disable it and choose ESync, which you have done now :-)
