### ISSUE TITLE
[Bug]:  Ubisoft not working

### ISSUE THREAD

**Issue by JoseHuertasDev** [IsaacMarovitz/Whisky#172]
### Description

Well, I've created an environment from scratch and installed Ubisoft connect, it's not opening

### Steps to reproduce

1. Crate a bottle from scratch
2. Install ubisoft connect
3. Try to open it
4. It will not open

### Expected behaviour

Ubisoft connect opening

### Logs

```bash
I don't have it
```

### What version of Whisky are you using?

pre-0.3.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Mika412** [comment]
Seems to be working on 1.0.0 release. Just takes a while to start

![image](https://github.com/IsaacMarovitz/Whisky/assets/5073663/e5735657-f366-4d64-9601-d2b4a8d7edcf)
