### ISSUE TITLE
[Bug]: Lego Worlds crash

### ISSUE THREAD

**Issue by J0ssel1n** [IsaacMarovitz/Whisky#173]
### Description

When I open the game, it closes instantly with no error message.

### Steps to reproduce

I made a little video: https://we.tl/t-lFca6mz6Fu

### Expected behaviour

I guess there's a problem with Direct X or something. Knowing that the game runs on Direct X 11

### Logs

```bash
Whisky Version: pre-0.3.1
Date: 27/06/2023 11:20:39
macOS Version: Version 14.0 (assemblage 23A5276g)
Bottle Name: Steam
Wine Version: 7.7
Windows Version: win10
Bottle URL: /Users/josselin/Library/Containers/com.isaacmarovitz.Whisky/Bottles/Steam

Arguments: start /unix /Users/josselin/Library/Containers/com.isaacmarovitz.Whisky/Bottles/Steam/drive_c/Program Files (x86)/Steam/steam.exe 

Launched Wine (4628)
0204: thread_get_state failed on Apple Silicon - faking zero debug registers
0324: thread_get_state failed on Apple Silicon - faking zero debug registers
Process exited with code 0
```

### What version of Whisky are you using?

pre-0.3.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by benwaco** [comment]
Running fine for me, where did you download the game?

![CleanShot 2023-06-27 at 21 57 31](https://github.com/IsaacMarovitz/Whisky/assets/127471645/61b95f1e-d671-4bcb-9971-8bdc93bf4cb0)

**Comment by J0ssel1n** [comment]
Can you tell me the steps to reproduce? As you can see, I downloaded it from Steam but I may have done something wrong.

Now I use crossover with cxpatcher to run the game and it works fine.

I'm staying with Crossover temporarily because I don't want to pay for it! If I could stay with a free, open-source solution

**Comment by benwaco** [comment]
> Can you tell me the steps to reproduce? As you can see, I downloaded it from Steam but I may have done something wrong.
> 
> Now I use crossover with cxpatcher to run the game and it works fine.
> 
> I'm staying with Crossover temporarily because I don't want to pay for it! If I could stay with a free, open-source solution.
> 
> (Also, thanks for your help)

I didn't do anything special besides using a not so legitimate version of the game. Might I suggest a full Whisky reset and a new bottle:

```
killall Whisky
rm -rf ~/Library/Application Support/Whisky/
```

**Comment by benwaco** [comment]
> Can you tell me the steps to reproduce? As you can see, I downloaded it from Steam but I may have done something wrong.
> 
> Now I use crossover with cxpatcher to run the game and it works fine.
> 
> I'm staying with Crossover temporarily because I don't want to pay for it! If I could stay with a free, open-source solution.
> 
> (Also, thanks for your help)

I am using the latest development build of Whisky (built from this repo) and a cracked copy of the game. I would suggest resetting your Whisky install and making a new bottle:

```
killall Whisky
rm -rf ~/Library/Application Support/Whisky/
```

Restart Whisky afterwards.


I am not sure if the development build of Whisky is any different in terms of Wine however it does appear to have a newer Wine install as it downloads Wine on the first launch. Feel free to build the latest commit here or if you need a copy I can help you out with one on Discord.

**Comment by J0ssel1n** [comment]
Yes, if you can help me on Discord that would be great. I think it's a problem with gptk because I tried the CX patcher by patching with gptk with the new method (https://github.com/italomandara/CXPatcher#patching-with-a-new-external-framework) and on Crossover it doesn't work anymore.

**Comment by benwaco** [comment]
> Yes, if you can help me on Discord that would be great. I think it's a problem with gptk because I tried the CX patcher by patching with gptk with the new method (https://github.com/italomandara/CXPatcher#patching-with-a-new-external-framework) and on Crossover it doesn't work anymore.

Feel free to add me, username is wood.bury.
