### ISSUE TITLE
[Feature]: Addition of winetricks

### ISSUE THREAD

**Issue by K0K1-0928** [IsaacMarovitz/Whisky#179]
### Is your feature request related to a problem?

Currently, steamwebhelper.exe crashes when trying to launch Steam in a Japanese environment.
This seems to be caused by Whisky's wine not including MS Gothic, which seems to be a common problem when using wine in Japanese.
To solve this, fonts need to be added and I would like to see winetricks added to Whisky as a way to do this.

### Describe the solution you'd like

The goal of this request is to be able to run `winetricks cjkfonts` in Whisky.

For example, if I place the `msgothic.ttc` file in `~/Library/Application Support/Whisky/Libraries/Wine/share/wine/fonts`, Steam will start fine.
However, placing `msgothic.ttc` is not desirable due to Microsoft conventions, so we prefer to misidentify the font with `winetricks cjkfonts` or similer as in conventional wine.

### Anything else?

`~/Library/Application Support/Whisky/Libraries/Wine/share/wine/fonts/msgothic.ttc` does not exist.
<img width="700" alt="image" src="https://github.com/IsaacMarovitz/Whisky/assets/27192117/6910c592-49df-4252-89fe-78cee8dae2c7">

`~/Library/Application Support/Whisky/Libraries/Wine/share/wine/fonts/msgothic.ttc` exists.
<img width="1276" alt="202306291942_steam_japanese" src="https://github.com/IsaacMarovitz/Whisky/assets/27192117/6b92d4f5-9d0c-4a33-b5cc-a0afc3f8297c">

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
The CJK issue is likely fixable with the following registry edit  key`HKEY_CURRENT_USER\Software\Wine\Fonts\Replacements`, value `Meiryo`, data `Microsoft YaHei`

**Comment by IsaacMarovitz** [comment]
Weird, I can't recreate this issue with stock Whisky wine
<img width="1280" alt="Screenshot 2023-07-01 at 00 17 43" src="https://github.com/IsaacMarovitz/Whisky/assets/42140194/bd1c3b9f-b170-4731-8701-c16f31a3b8b2">

**Comment by K0K1-0928** [comment]
Unfortunately, editing the registry did not improve the situation.
(We tried to Replace not only `Meiryo` , but also `MS Gothic` and `MS Mincho` , but failed.)
If the Japanese switching is working well in your environment, it may be influenced by the language settings at the time of Bottle creation.
I am not familiar with wine itself or the font handling within wine, so I may not be able to provide accurate information. My apologies, I'm not sure how to fix this.
Thank you very much for your advice, it is much appreciated!
<img width="1265" alt="image" src="https://github.com/IsaacMarovitz/Whisky/assets/27192117/876f3381-c808-4413-81cd-6a1cf88ea2d0">
<img width="696" alt="image" src="https://github.com/IsaacMarovitz/Whisky/assets/27192117/e6140f8d-b4ab-4b34-8018-3dcbdd15f639">

**Comment by TurtleRanking** [comment]
I _think_ in the meantime you could run the following.

```
your_bottle_guid=00-00-00-00
PATH="$HOME/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/Wine/bin:$PATH" \
WINE=wine64 \
WINEPREFIX="$HOME/Library/Containers/com.isaacmarovitz.Whisky/Bottles/$your_bottle_guid" \
winetricks cjkfonts
```

You'll need winetricks installed and on your path (I used the Homebrew one), and of course change the `your_bottle_guid` value to whatever the relevant folder in `$HOME/Library/Containers/com.isaacmarovitz.Whisky/Bottles` is called .

**Comment by K0K1-0928** [comment]
What @TurtleRanking suggested worked brilliantly!
Thank you so much for helping me!

This Issue itself is left open, as it is my hope that winetricks functionality will be added to Whisky.

As an aside, Instead of `cjkfonts` , `fakejapanese_ipamona` might have been more appropriate.

**Comment by amartinez1660** [comment]
Pardon my ignorance, but would this 'winetricks' help to get an older game running?
I have been trying from time to time to just run Diablo (the very first one with Hellfire, from GoG), the whole Whisky app has been overhauled so much every update that now I manage to install it via the setup.exe file directly and then can even get to the game launcher.
I get a

**Comment by IsaacMarovitz** [comment]
Winetricks added upstream
