### ISSUE TITLE
[Bug]: Steam wont load 

### ISSUE THREAD

**Issue by natsukirei** [IsaacMarovitz/Whisky#185]
### Description

hey guys, so basically i have a windows 10 bottle for diablo iv and it runs fine but i cant run steam in it, i am not sure how to get it to work

It installs and updates then nothing happens it just exits and does not come back

### Steps to reproduce

add the steam installer to a bottle and run it

### Expected behaviour

steam loads to the UI

### Logs

```bash
unsure
```

### What version of Whisky are you using?

pre-0.3.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by minskiter** [comment]
Me too. I disabled Steam updates to fix this. But it says "steamui.dll not found". GPTK doesn't seem to support the latest steam. I also tried installing the GPTK manual, same.

**Comment by Quinten0508** [comment]
Seems to work fine with the latest GH release (1.0.0) on my M1 macbook air. Is the issue still present after updating? Try creating a fresh bottle and make sure to use GPTK 1.0.2.

**Comment by minskiter** [comment]
> Seems to work fine with the latest GH release (1.0.0) on my M1 macbook air. Is the issue still present after updating? Try creating a fresh bottle and make sure to use GPTK 1.0.2.

This issue was solved after I updated. #200
