### ISSUE TITLE
[Bug]: GTA V loading screen

### ISSUE THREAD

**Issue by MacM2Pro** [IsaacMarovitz/Whisky#186]
### Description

GTA V Rockstar Launcher version is endlessly loading to the story mode.
UPD: 1.0 version also same problem

### Steps to reproduce

I have installed Rockstar Games Launcher in a bottle, then tried to start GTA V. I have tried starting both from launcher and as PlayGTAV.exe. Also tried Esync, DXVK functions and disabling cloud saving, verified integrity. 

### Expected behaviour

Game doesn't start, l was waiting almost an hour

### Logs

```bash
Whisky Version: pre-0.3.1
Date: 2023/07/02, 12:47:16
macOS Version: Version 14.0 (Build 23A5276g)
Bottle Name: rockstar
Wine Version: 7.7
Windows Version: win10
Bottle URL: /Users/datum/Library/Containers/com.isaacmarovitz.Whisky/Bottles/rockstar

Arguments: start /unix /Users/datum/Library/Containers/com.isaacmarovitz.Whisky/Bottles/rockstar/drive_c/Program Files/Rockstar Games/Launcher/LauncherPatcher.exe 

Launched Wine (2005)
06f0:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
```

### What version of Whisky are you using?

pre-0.3.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ajinkyatalekar** [comment]
I am fairly certain this has to do with the fact that Whisky does not ask for permission to use microphone.
I have the same issue. GTA V runs fine when I run it with Game Porting Toolkit the normal way with terminal, and terminal asks for microphone permission. However, Whisky does not do this and ends up being stuck in the loading screen.

**Comment by hkraenzle** [comment]
Solution or workaround would be great

**Comment by MacM2Pro** [comment]
> I am fairly certain this has to do with the fact that Whisky does not ask for permission to use microphone. I have the same issue. GTA V runs fine when I run it with Game Porting Toolkit the normal way with terminal, and terminal asks for microphone permission. However, Whisky does not do this and ends up being stuck in the loading screen.

Thank you for sharing. I have read about this microphone prompt issues in other threads before but have never seen such a thing. In my case, Whisky is the only program that managed to start Rockstar Launcher and Steam. I haven't tried Crossover yet but I tried GPT, Wine and even WineBottler and Harbor, and all of them just crashed while starting with "steamwebhelper.exe (or socialclubhelper.exe) has encountered a serious problem".

**Comment by MacM2Pro** [comment]
> Solution or workaround would be great

Good news everyone! The bug has disappeared after the release of a new Sonoma beta 3 version! Please check if you have an update pending.
