### ISSUE TITLE
How to update the GPTK DMG file in Whisky after the update?

### ISSUE THREAD

**Issue by keef-khan** [IsaacMarovitz/Whisky#199]
GPTK got a 1.0.2 release two days ago. Notably the download size is only half of the original. How can I update the one that Whisky uses?

![Screenshot 2023-07-03 at 1 31 47 PM](https://github.com/IsaacMarovitz/Whisky/assets/67087783/c7d49440-82c8-4e5b-bdb1-b8c6c9e00a64)

**Comment by zoemaestra** [comment]
Delete the Libraries folder at `~/Library/Application Support/Whisky`

**Comment by zhufucdev** [comment]
I implemented this in #205 

just wait...

**Comment by focher** [comment]
Strangely, I do not have a folder in the Libraries folder at ~/Library/Application Support/Whisky.

However, I did find it under ~/Library/Application Support/com.isaacmarovitz.Whisky 

I used Homebrew to install Whisky.

**Comment by IsaacMarovitz** [comment]
> Strangely, I do not have a folder in the Libraries folder at ~/Library/Application Support/Whisky.

We changed the location at some point before 1.0. Finder will show the folder name as "Whisky", but that actual path is `com.isaacmarovitz.Whisky`
