### ISSUE TITLE
[Feature]: Detect when old GPTK files are used and prompt the user to update them

### ISSUE THREAD

**Issue by UltraHDR** [IsaacMarovitz/Whisky#200]
### Is your feature request related to a problem?

Whisky 1.0.0 allows you to use the files from "Game_porting_toolkit_beta.dmg" when "Game_porting_toolkit_beta_1.02.dmg" already exists. Additionally, updating requires a manual step https://github.com/IsaacMarovitz/Whisky/issues/199#issuecomment-1618950469

### Describe the solution you'd like

1. Save the sha1sum of the Game Porting Toolkit files and prompt the user to update them when they're old.
2. Prompt the user and allow them to "update", "prompt next time", "Never prompt for this version" (This is useful if a newer version has a bug in it)

### Anything else?

I deleted ~/Library/Application\ Support/Whisky/Libraries/Wine/lib/* and restarted Whisky but I didn't get the prompt to drag the dmg into Whisky. I had to run "brew reinstall --cask whisky --zap"

### Issue Language

- [X] Yes my issue is written in English

**Comment by jcnelson30** [comment]
Just to add onto this, maybe somewhere in the menu to "change gptk version". I know some people had issues with 1.0.2 and making it easy to go back to 1.0.0

**Comment by kode54** [comment]
Um, this may be a good time to point out that the Wine part of GPTK was updated as well? They probably both need to be in sync with each other.

**Comment by JoshuaBrest** [comment]
> Um, this may be a good time to point out that the Wine part of GPTK was updated as well? They probably both need to be in sync with each other.

@kode54 
when we download wine, we don't *actualy* download wine, we just download additional support libs.

**Comment by kode54** [comment]
Then where are you getting Wine?

This may also be a great time to point out that I can't actually get GPTK's Homebrew part to build as of 1.02. Fails at the same place every time. I've filed FB12540379 with Apple, in case they care about releasing non-functional developer toolkits.

**Comment by JoshuaBrest** [comment]
> Then where are you getting Wine?
> 
> This may also be a great time to point out that I can't actually get GPTK's Homebrew part to build as of 1.02. Fails at the same place every time. I've filed FB12540379 with Apple, in case they care about releasing non-functional developer toolkits.
> 
> ```
> ld: unknown options: -segaddr
> ```

gptk

**Comment by IsaacMarovitz** [comment]
> Um, this may be a good time to point out that the Wine part of GPTK was updated as well? They probably both need to be in sync with each other.

Hasn't been an issue with GPTK 1.0.0 vs 1.0.2

**Comment by IsaacMarovitz** [comment]
We do already prompt for old Wine install, and there are some cases where an older version of GPTK is preferred, so I'm gonna close this for now
