### ISSUE TITLE
Windows version 

### ISSUE THREAD

**Issue by matvada** [IsaacMarovitz/Whisky#204]
Hello, thank you for this amazing software!
I have a problem with Steam launching a game:

The system warns me to have a newer version of Windows 10 (version 1909 build 18363) instead of 18362 installed on Whisky.
Is there a way to fix this problem?

Thanks!

**Comment by Mika412** [comment]
You can change the Windows build version in the bottle config

**Comment by matvada** [comment]
Thank you,
i tried before open the ticket but maybe i forgot to press enter :D

Super!
Thanks
