### ISSUE TITLE
[Feature]: allow user to use homebrew wine-devel package

### ISSUE THREAD

**Issue by anyuzu99** [IsaacMarovitz/Whisky#207]
### Is your feature request related to a problem?

the default wine version is reletively old, if whisky could find brew `wine-devel`, `wine-stable`, `wine-staging`, it could be much easier to upgrade the wine version.

### Describe the solution you'd like

find brew wine

### Anything else?

nothing

### Issue Language

- [X] Yes my issue is written in English

**Comment by anyuzu99** [comment]
CrossOver 23 has released. now we can have wine 8.0

**Comment by IsaacMarovitz** [comment]
> CrossOver 23 has released. now we can have wine 8.0

It is not that simple. Apple will have to do the work to update GPTK to be based on Wine 8.
