### ISSUE TITLE
[Feature]: export / copy bottles from UI

### ISSUE THREAD

**Issue by jcnelson30** [IsaacMarovitz/Whisky#208]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

The bottles listed in the UI - can we have simply copy/export abilities maybe via “right click”? 

In the experimental nature of this system, a few times I have wanted to change some bottles settings or files in the bottle (ie unpacking data files for faster load times) in addition to changing gptk versions.

I wasn’t sure if I broke the bottle / whisky etc, so having a reliable copy point goes a long way into diagnosing it.

I do understand copying these game bottle installs is large, but can help the multiple reinstalls I had to do the other day

### Anything else?

No

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Added exporting upstream
