### ISSUE TITLE
[Info]: What is Whisky actually doing? Where was Wine downloaded to? Why are there two bottles?

### ISSUE THREAD

**Issue by vesper8** [IsaacMarovitz/Whisky#209]
### Is your feature request related to a problem?

So, I've been using GPTk since it was announced in early June, it's working perfectly.

I gave Whisky a try today, first thing I was a bit disappointed with is that it said Wine wasn't installed and GPTk wasn't installed, even though both are obviously installed since I'm using them.

I clicked next, unsure about what was going to happen next, and it started downloading Wine, and then forced me to drag-n-drop the GPTk dmg file. I tried to abort but was unable to.

So I wonder, where was Wine downloaded/installed to now? I want to know because I want to possibly uninstall it.

Also what did it do with the GPTk I drag-n-dropped ? Where did it copy these files?

I think more transparency about what is actually happening would be good.

I also had a look in the container bottles in ~/Library. It created two seemingly identical bottles, both take up 1.23GB of space. It added the letter 'x' at the end of the bottle that I named, unsure why.

### Describe the solution you'd like

More transparency about everything it's doing, and how to uninstall all this so nothing is left behind?

### Anything else?

Explaining why two bottles were created.

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Whisky does not use existing Wine or GPTK installations. We use a prebuilt Wine package with some extra patches to make it work better as a library. That builder is available [here](https://github.com/IsaacMarovitz/WhiskyBuilder). Wine and GPTK is installed to `~/Application Support/com.isaacmarovitz.Whisky/Libraries`. The identical bottles thing sounds wrong.

A full list of directories that Whisky installs to is available in [Whisky's cask](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/whisky.rb).

As for transparency, the entire source code is freely available here on GitHub. Not sure how I can be more transparent than that.
