### ISSUE TITLE
“Whisky” is damaged and can’t be opened. You should move it to the Trash.

### ISSUE THREAD

**Issue by montanaflynn** [IsaacMarovitz/Whisky#21]
I downloaded the Whisky.app.zip file from the pre-0.2.0 release:

https://github.com/IsaacMarovitz/Whisky/releases/tag/pre-0.2.0

I'm on a fresh install of Sonoma and get this when trying to open the Whisky app. I also tried not adding the lib folders from the Game Porting Kit in case that was causing the issue but even without changing anything I get this error:

<img width="288" alt="Screenshot 2023-06-07 at 10 36 46 PM" src="https://github.com/IsaacMarovitz/Whisky/assets/24260/554cc581-8c04-4e93-8aec-0075230aa515">

I also tried right-click open and same thing.

**Comment by treblechet** [comment]
Delete the whiskey.app, redownload (or just reextract from the zip), do not try and open the app until you copy the lib folder over.

**Comment by 0x346e3730** [comment]
If @treblechet's answer doesn't work, run `xattr -d com.apple.quarantine <path-to-app>` and re-launch Whisky.

**Comment by augustomegres** [comment]
> If @treblechet's answer doesn't work, run `xattr -d com.apple.quarantine <path-to-app>` and re-launch Whisky.

It works here

**Comment by jipiboily** [comment]
Getting this error on Ventura. `xattr -d com.apple.quarantine <path-to-app>` (with my path updated) doesn't seem to change anything.

I also tried deleting the app, and re-downloading + extracting again. Same result.

As a note, I manually installed a few things yesterday from the Game Porting Toolkit. No idea if this could have an effect.

I'm on `13.4 (22F66)` on a M1 Max, if that can help.
