### ISSUE TITLE
[Bug]: Wine version 7.7.0 while 8.0.1 installed

### ISSUE THREAD

**Issue by xexets** [IsaacMarovitz/Whisky#210]
### Description

Hello, is there a reason why my new bottles are launched with Wine 7.7.0? I have Wine 8.0.1 installed via brew.
Thanks

### Steps to reproduce

In new bottle click on info or look at log. All report Wine 7.7.0 while I have 8.0.1 installed

### Expected behaviour

I assume it would use the latest version of wine?

### Logs

```bash
Whisky Version: 1.0.0
Date: 05/07/2023, 9:54:01
macOS Version: Version 14.0 (Build 23A5276g)
Arguments: --version 

Launched Wine (6423)
wine-7.7
Process exited with code 0
```

### What version of Whisky are you using?

1.0.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Whisky cannot and will not use Wine installed via brew. This is not a bug.
