### ISSUE TITLE
[Feature]: The choice to have engines and bottles inside or out, of the Whisky.app

### ISSUE THREAD

**Issue by ferreira-ff** [IsaacMarovitz/Whisky#211]
### Is your feature request related to a problem?

I start, writing thank you very much for your great work, making the option of running games on Mac much more easier.

My feature request is not related to a problem. It is more, like a matter of choice...

I am a big fan of Wineskin, because I can have a "compartmentalized" application or game, without the need to have files spread, all over the Library folder.
<img width="230" alt="Captura de ecrã 2023-07-05, às 18 34 25" src="https://github.com/IsaacMarovitz/Whisky/assets/138707753/6fa2cd21-5e43-490d-849a-8dd0b537b46d">

### Describe the solution you'd like

It would be great if the Whisky Application could let us choose, where to install the engines and bottles:

_1) Engines and bottles inside the Library folder. Good for, eg: Steam and games._
_2) Engines and bottles inside of the Whisky.app. Good for, eg: one game from GOG._
<img width="120" alt="Captura de ecrã 2023-07-05, às 18 45 58" src="https://github.com/IsaacMarovitz/Whisky/assets/138707753/fe59352b-08d3-467a-b0b0-110531b54b51">

### Anything else?

Still testing. Nothing more, for now.

Kind regards to all.

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Making runtime modifications to Whisky.app is not feasible, as that will violate the code signature and cause all sorts of problems. What's the problem with having everything installed within the Library folder?

**Comment by ferreira-ff** [comment]
Hello. Yes; you are completely right, that was probably a bad suggestion; maybe it is my obsession, with perfectionism. I ended up fixing it to my liking, with "symlinks"... now, everything is inside the Whisky application.

Again; thank you for the superb work , from you and the contributors. Kind regards to all.
