### ISSUE TITLE
[Bug]: Black Mesa Won't Work

### ISSUE THREAD

**Issue by cirava** [IsaacMarovitz/Whisky#213]
### Description

Whenever I start Black Mesa it gets to the splash screen with the developer credits, then it immediately crashes.

### Steps to reproduce

1. Install Steam
2. Install Black Mesa
3. Hit the play button

### Expected behaviour

I would expect the game to at least launch and get to the menu, even if the frames aren't the best.

### Logs

```bash
I don't have one
```

### What version of Whisky are you using?

1.0.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [x] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
<img width="1440" alt="Screenshot 2023-07-06 at 12 29 29" src="https://github.com/IsaacMarovitz/Whisky/assets/42140194/2be1f023-5922-47ad-b910-927d9e70c84b">

Black Mesa is a DX9 game, so you must enable DXVK. Works for me but the modern UI parts don't render.
