### ISSUE TITLE
[Bug]: GTA V Visual Glitches

### ISSUE THREAD

**Issue by MacM2Pro** [IsaacMarovitz/Whisky#215]
### Description

GTA V invisible guns, weird green car windows, weird brightness indoors and reflection artifacts
![image](https://github.com/IsaacMarovitz/Whisky/assets/138347379/91bd5f4b-b095-45c5-89ca-63593aeca948)
![Screenshot 2023-07-07 at 1 07 54](https://github.com/IsaacMarovitz/Whisky/assets/138347379/7b3ef4c3-adc9-4332-a2e8-8be3c5c8edaf)

### Steps to reproduce

GTA V Rockstar Launcher version. Tried to toggle windows version, dxvk, esync, retina, some in-game graphics.

### Expected behaviour

Graphics issues

### Logs

```bash
Whisky Version: 1.0.0
Date: 2023/07/07, 0:59:11
macOS Version: Version 14.0 (Build 23A5286g)
Bottle Name: rockstar
Wine Version: 7.7.0
Wine Binary Version: 4
Windows Version: win10
Bottle URL: /Users/datum/Library/Containers/com.isaacmarovitz.Whisky/Bottles/6DE4550F-25E9-4CA4-A7B2-CBF02E1C1A97

Arguments: reg query HKCU\Software\Wine\Mac Driver -v RetinaMode 

Launched Wine (1886)

HKEY_CURRENT_USER\Software\Wine\Mac Driver
    RetinaMode    REG_SZ    n

Process exited with code 0
```

### What version of Whisky are you using?

1.0.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
You seem to have uploaded the wrong log file.

It is likely that this is a D3DM issue, in which case, there isn't much we can do, but there are a few things you can try. Disable DXVK, and make sure that in-game, you are using the DirectX 11 renderer instead of the DirectX 10 one. See if that has any improvement. 

Windows version, Esync, and Retina Mode will not help you here.

**Comment by MacM2Pro** [comment]
> You seem to have uploaded the wrong log file.
> 
> It is likely that this is a D3DM issue, in which case, there isn't much we can do, but there are a few things you can try. Disable DXVK, and make sure that in-game, you are using the DirectX 11 renderer instead of the DirectX 10 one. See if that has any improvement.
> 
> Windows version, Esync, and Retina Mode will not help you here.

Thank you for your concern. Yeah, I'm not sure which log file I should use. I have uploaded the latest out of console log reports that includes Whisky.

Anyway, I have already tried using in-game DirectX 11 with DXVK disabled, this is kinda default configuration.

**Comment by MacM2Pro** [comment]
Green car windows FIXED with in-game settings. Just turned on the MSAA. Still investigating other bugs.

**Comment by CMMChris** [comment]
Had the same issue. It's caused by running through DXVK. When you toggle the metal HUD you will notice the game not running through D3DMetal. Had to open WineCFG and remove all the D3D entries present in the library override section. After doing so, GTA V uses D3DMetal without the graphical glitches. The Metal HUD then shows "D3D11". Also doubles performance compared to DXVK on my M2 Max.

**Comment by MacM2Pro** [comment]
> Had the same issue. It's caused by running through DXVK. When you toggle the metal HUD you will notice the game not running through D3DMetal. Had to open WineCFG and remove all the D3D entries present in the library override section. After doing so, GTA V uses D3DMetal without the graphical glitches. The Metal HUD then shows "D3D11". Also doubles performance compared to DXVK on my M2 Max.

Thank you for this idea, but in my case removing d3d and dxgi (= turn off dxvk) makes the game's graphics settings unswitchable, and the game stucks with some low-res windowed mode. Idk, probably this should be considered as a separate bug, anyway removing them really fixed the visual glitches.

**Comment by CMMChris** [comment]
This is normal GPTK behavior. Game will use the screen or scaled resolution set within the macOS system preferences. Set to borderless windowed in game and it will be rendered full screen. Might need to restart the game.

**Comment by MacM2Pro** [comment]
> This is normal GPTK behavior. Game will use the screen or scaled resolution set within the macOS system preferences. Set to borderless windowed in game and it will be rendered full screen. Might need to restart the game.

Oh, man, thank you very much!

**Comment by Lipooooo** [comment]
> This is normal GPTK behavior. Game will use the screen or scaled resolution set within the macOS system preferences. Set to borderless windowed in game and it will be rendered full screen. Might need to restart the game.

Do you have a fix for launching the game directly with the res of 1080 p instead the mac res ?

**Comment by simonepri** [comment]
For posterity this is still an issue. I got it to work by disabling `DXVK`.

When you disable `DXVK` you will get this error from the launcher (which is probably the reason why you enabled `DXVK` in the first place):
<img width="325" alt="image" src="https://github.com/Whisky-App/Whisky/assets/3505087/7fb044d3-93d4-4b0e-be4d-e3f3ea34c65d">

To workaround this, Go to "Bottle Configuration"
<img width="1156" alt="image" src="https://github.com/Whisky-App/Whisky/assets/3505087/137caca9-f4e2-491b-bf14-70e6b25f73aa">

Then click "Open Win Configuration", click "Add application" and add `Launcher.exe` (e.g. most likely from C:\Program Files\Rockstar Games\Grand Theft Auto V).

<img width="412" alt="image" src="https://github.com/Whisky-App/Whisky/assets/3505087/74c6c393-93c1-4b52-b466-318f8d7aaa94">

Then click on the "Libraries" tab and the following overrides:

<img width="412" alt="image" src="https://github.com/Whisky-App/Whisky/assets/3505087/035bee08-afb2-475f-8871-87547e6a2f9f">

Then click "Apply" and you are done.

Now you should be able to start GTA V from Steam without enabling `DXVK`.

Cheers!

**Comment by JSP100** [comment]
This workaround no longer works for me after a full system reset (via DFU mode), however I managed to get the game up and running by adding one more library override on top of your modifications. 

This is the settings I use: <img width="522" alt="Screenshot 2024-07-27 at 19 27 47" src="https://github.com/user-attachments/assets/7b28a14d-a09c-4b42-80e9-c0ec94a4f3cc">

(PS. I am not sure that this will work for everyone)

**Comment by daniil-pogorelov** [comment]
Hey! Thank you all for your fixes. Rn I am facing one texture glitch with pants, gloves, and eyes in GTA Online. Maybe someone has an idea of what's going on. I am not using DXVK, I made the same setup as in the previous post here.

PS: I understand that this type of problem is normally related to graphic drivers (I am a beginner in Wine so I don't know how to troubleshoot it)

System:
MacBook Air M1, 8GB
macOS 14.2.1 (23C71)
Whisky and WhiskyWine are up to date


<img width="1280" alt="Screenshot 2024-08-02 at 14 08 21" src="https://github.com/user-attachments/assets/7d12fdf6-2d3f-49ef-9964-726bb3c85745">
<img width="1280" alt="Screenshot 2024-08-02 at 14 08 40" src="https://github.com/user-attachments/assets/dc3da65f-87a4-4c02-bc50-ca0f2826149c">
<img width="1280" alt="Screenshot 2024-08-02 at 14 09 09" src="https://github.com/user-attachments/assets/e91b5807-d9fb-4c86-9523-f7aeb72ca67c">
<img width="1280" alt="Screenshot 2024-08-02 at 14 08 52" src="https://github.com/user-attachments/assets/0d1142ed-5d0a-4174-ada9-de88ab60ae1f">

**Comment by daniil-pogorelov** [comment]
> Hey! Thank you all for your fixes. Rn I am facing one texture glitch with pants, gloves, and eyes in GTA Online. Maybe someone has an idea of what's going on. I am not using DXVK, I made the same setup as in the previous post here.
> 
> PS: I understand that this type of problem is normally related to graphic drivers (I am a beginner in Wine so I don't know how to troubleshoot it)
> 
> System: MacBook Air M1, 8GB macOS 14.2.1 (23C71) Whisky and WhiskyWine are up to date
> 
> <img alt="Screenshot 2024-08-02 at 14 08 21" width="1280" src="https://private-user-images.githubusercontent.com/35654488/354604909-7d12fdf6-2d3f-49ef-9964-726bb3c85745.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4Njg4NDgsIm5iZiI6MTcyMjg2ODU0OCwicGF0aCI6Ii8zNTY1NDQ4OC8zNTQ2MDQ5MDktN2QxMmZkZjYtMmQzZi00OWVmLTk5NjQtNzI2YmIzYzg1NzQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDE0MzU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNDg5NDEzMzIwMTc0OTJlYjI0MTRlY2VmYjY1YzZlMDNmMjdkZTFkODc0NWE2M2E5ZjgzOTM1ZWNiOTk4NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NL5dB9N1PuLnBgsZVnVkng0zz71nV-uB7XW25zvlvmI"> <img alt="Screenshot 2024-08-02 at 14 08 40" width="1280" src="https://private-user-images.githubusercontent.com/35654488/354604933-dc3da65f-87a4-4c02-bc50-ca0f2826149c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4Njg4NDgsIm5iZiI6MTcyMjg2ODU0OCwicGF0aCI6Ii8zNTY1NDQ4OC8zNTQ2MDQ5MzMtZGMzZGE2NWYtODdhNC00YzAyLWJjNTAtY2EwZjI4MjYxNDljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDE0MzU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhZWZjNmY0YjAzNzZkNzc2ZTBjMDNlNDRiN2ZmOWNkN2U2NDBhZGIzZDk2MjE2YzZiMGE4ZmNlNmI4MDFjNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2QJq6ADmiPG0PizNb2DhUy6IaKdOXOsLLbNI0dOF1lA"> <img alt="Screenshot 2024-08-02 at 14 09 09" width="1280" src="https://private-user-images.githubusercontent.com/35654488/354604956-e91b5807-d9fb-4c86-9523-f7aeb72ca67c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4Njg4NDgsIm5iZiI6MTcyMjg2ODU0OCwicGF0aCI6Ii8zNTY1NDQ4OC8zNTQ2MDQ5NTYtZTkxYjU4MDctZDlmYi00Yzg2LTk1MjMtZjdhZWI3MmNhNjdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDE0MzU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2M2Y0OGNhNTA4ODFhNzllMTZhZjhjNmU1YTBmZmJhZDY1ZTdhMDk1M2M2MTRhODIwYjk3YzNhY2FkN2NiYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.toyWxLlwOXgH2L81TShE_RqdsmVBIxLuf60bUQSQO08"> <img alt="Screenshot 2024-08-02 at 14 08 52" width="1280" src="https://private-user-images.githubusercontent.com/35654488/354604949-0d1142ed-5d0a-4174-ada9-de88ab60ae1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4Njg4NDgsIm5iZiI6MTcyMjg2ODU0OCwicGF0aCI6Ii8zNTY1NDQ4OC8zNTQ2MDQ5NDktMGQxMTQyZWQtNWQwYS00MTc0LWFkYTktZGU4OGFiNjBhZTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDE0MzU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1OWYzOWNmYTE2NWQzYjI4MTFhMTRiYTVlYWZmNzlmNTdmZjg4NjMwYjA4ZjcwMDBiNzhjYzZiY2M1NmE3OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qLouUuoGUXI0WnrDrem_aRUf41ZLDGpvIq_UFX01iAg">

Fixed by using GPTK 1 ¯\_(ツ)_/¯

**Comment by simonepri** [comment]
> his workaround no longer works for me after a full system reset

@JSP100 I'm experiencing a similar issue after restoring my macbook to factory. The game installs via Steam but nothing happens when I hit play on Steam.
It used to be the case that when playing the first time one would encounter the rockstar games launcher errors discueed before, but now nothing happens at all now.

There was a recent game update that might have updated the launcher or something.
