### ISSUE TITLE
[Feature]: Change Versions And Update Via The Program

### ISSUE THREAD

**Issue by xnuken** [IsaacMarovitz/Whisky#216]
### Is your feature request related to a problem?

Not that I am aware of

### Describe the solution you'd like

The ability to change Game Porting Toolkit versions and automatically update dependencies for Game Porting Toolkit and the tool its self

### Anything else?

None

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
GPTK installer added
