### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by akxks** [IsaacMarovitz/Whisky#217]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

While the Whisky App Ui is fairly simple, could add a few additional text and information to bottles, such as a text saying "Whisky / GPTK only supports DX11/12 for now"

as DX9 games can't run, just so that people know and don't waste time trying to run things that won't work

### Anything else?

That's it.

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
DirectX 9 games can run. You just need to enable DXVK.
