### ISSUE TITLE
[Bug]: Opening CMD/Opening Program as Administrator

### ISSUE THREAD

**Issue by jackokeeffe** [IsaacMarovitz/Whisky#218]
### Description

For some programs where one has to open it as administrator, since you are unable to right-click the programs and ddo so you are forced to use CMD. How can you open CMD in Whiskey without the application showing in the program files

### Steps to reproduce

N/A

### Expected behaviour

Should be able to open program as administrator, specifically Steam

### Logs

```bash
N/A
```

### What version of Whisky are you using?

1.0.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by jackokeeffe** [comment]
Opening the file menu in whiskey and attempting to right-click and find the compatibility tab for .exe applications also does not work.

**Comment by IsaacMarovitz** [comment]
Wine does not have a concept of 'Running as administrator'
