### ISSUE TITLE
[Feature]: Please don’t release the final version directly, but a beta version.

### ISSUE THREAD

**Issue by larryisthere** [IsaacMarovitz/Whisky#226]
### Is your feature request related to a problem?

Every time new version released, the fatal bugs came as well. Diablo IV or battlenet launcher does not run normally. We don’t call this is a release.

### Describe the solution you'd like

Insert a beta version instead of any final release. And don’t push any beta version when automatic update.

### Anything else?

No.

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
That's your opinion. Diablo IV is just one of thousands of games.

**Comment by ohaiibuzzle** [comment]
My disappointment in humanity is immeasurable and my day is ruined
![image](https://github.com/IsaacMarovitz/Whisky/assets/23693150/89c49fae-ebeb-465b-aad3-29e94fcdbb1c)
