### ISSUE TITLE
[Bug]: Textures messed up in BeamNG.Drive

### ISSUE THREAD

**Issue by richstokes** [IsaacMarovitz/Whisky#228]
### Description

<img width="1728" alt="image" src="https://github.com/IsaacMarovitz/Whisky/assets/13403491/e5ed1732-b2e3-4b38-bfe7-3f730aa03147">

### Steps to reproduce

play the game. it seems to mostly affect ground textures

### Expected behaviour

not be graphical disturbances

### Logs

```bash
N/A
```

### What version of Whisky are you using?

1.0.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Looks like thres a fix https://github.com/SnoutBug/BeamNG_terrainMaterialCache
