### ISSUE TITLE
[Feature]: If possible, a way to fix the M1/M2 Ultra performance

### ISSUE THREAD

**Issue by ferreira-ff** [IsaacMarovitz/Whisky#231]
### Is your feature request related to a problem?

Maybe only Apple can resolve this, but I needed to ask:
The Apple's M1/M2 Max CPU + Whisky.app work perfectly, with almost everything we need to use.
The Apple's M1/M2 Ultra CPU + Whisky.app on some applications and games, have a very low performance, specialy from the GPU cores.

**The M2 Ultra behaves a little better than the M1 Ultra, but not by much...**

### Describe the solution you'd like

If it is possible; to add the possibility (flag?) to use only one CPU, when the system has more than one (Apple Silicon M1/M2 Ultra) so, when launching a "troubling" application or game, it would work correctly and with good performance.
![Apple-M1-chip-family-lineup-220308_big jpg large_2x](https://github.com/IsaacMarovitz/Whisky/assets/138707753/82de590a-645e-482a-b30f-862d17c5dfdc)

### Anything else?

The Whisky app and literally a glass of a good whiskey; it is getting better and better, at every new release :)
Kind regards to all.

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
No. 
Apple are so confident in UltraFusion that the chip presents itself as a single UMA chip, so there is none of that memory sharing shenanigans there
Even if you managed to get it to run on the CPUs that is on one side (using CPU affinity settings), you have no way to control the GPU the same way

**Comment by ferreira-ff** [comment]
> No. Apple is so confident in UltraFusion that the Ultra chips actually presents themselves as a single UMA chip, so there is none of those shenanigans here Even if you managed to get it to run on the CPUs that is on one side (using CPU affinity settings), you have no way to control the GPU the same way

Hello. Thank you very much, for taking the time and explain it to me; I understood the GPU part, very clearly. Cheers.

**Comment by IsaacMarovitz** [comment]
Apple is working on improving the performance internally.
