### ISSUE TITLE
[Bug]: Trackmania United Forever Running Abhorrently Slow

### ISSUE THREAD

**Issue by cirava** [IsaacMarovitz/Whisky#232]
### Description

I'm trying to play TMUF, and the menu navigation is pretty smooth, however as soon as I get in game it runs horribly slow. It's entirely unplayable, I'd even call it seconds per frame.

### Steps to reproduce

1. Install tmunitedforever_setup.exe from here http://files.trackmaniaforever.com/tmunitedforever_setup.exe (alternatively, TM Nations Forever is practically a free demo of this game, so this setup file may be better for figuring something out http://files.trackmaniaforever.com/tmnationsforever_setup.exe)
2. Run the installer as normal
3. Run TMForeverLauncher.exe
4. Click Play
5. Navigate the menus to be in game

### Expected behaviour

I expected the game to run at an at least semi-playable speed

### Logs

```bash
N/A
```

### What version of Whisky are you using?

1.0.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
This game is very very old, I can't get it to start on my machine. I recommend trying to modern Trackmania.

**Comment by j05hp** [comment]
+1 on this. TMNF is the same but runs even worse
