### ISSUE TITLE
[Bug]: Skyrim SE NPC sounds missing

### ISSUE THREAD

**Issue by frootloop88** [IsaacMarovitz/Whisky#233]
### Description

So I can run Skyrim SE by renaming the exe to skip the launcher but the sound is wrong. It works/no cracking etc. but it seems to think I use a 7.1 system so every npc or other audio coming from the front is not present/very very low volume

### Steps to reproduce

Launch Skyrim SE from steam and play

### Expected behaviour

Wrong audio

### Logs

```bash
Whisky Version: 1.0.1
Date: 11.7.2023, 22:18:57
macOS Version: Version 14.0 (Build 23A5286i)
Bottle Name: Steam
Wine Version: 7.7.0
Wine Binary Version: 4
Windows Version: win10
Bottle URL: /Users/frederik/Library/Containers/com.isaacmarovitz.Whisky/Bottles/3A0427CE-5CAC-4FF1-82B1-EB2D5A8B6963

Arguments: start C:\Program Files (x86)\Steam\steam.exe 

Environment:
{
    WINEDLLOVERRIDES = "dxgi,d3d9,d3d10core,d3d11=b";
}

Launched Wine (11527)
esync: up and running.
0144: thread_get_state failed on Apple Silicon - faking zero debug registers
017c: thread_get_state failed on Apple Silicon - faking zero debug registers
0184: thread_get_state failed on Apple Silicon - faking zero debug registers
0184: thread_get_state failed on Apple Silicon - faking zero debug registers
01ac: thread_get_state failed on Apple Silicon - faking zero debug registers
0184:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
01d8: thread_get_state failed on Apple Silicon - faking zero debug registers
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
0210: thread_get_state failed on Apple Silicon - faking zero debug registers
0238: thread_get_state failed on Apple Silicon - faking zero debug registers
[mvk-info] Created VkInstance for Vulkan version 1.1.0, as requested by app, with the following 2 Vulkan extensions enabled:
		VK_KHR_surface v25
		VK_EXT_metal_surface v1
025c: thread_get_state failed on Apple Silicon - faking zero debug registers
0288: thread_get_state failed on Apple Silicon - faking zero debug registers
0294:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
0294:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
02a8: thread_get_state failed on Apple Silicon - faking zero debug registers
02fc: thread_get_state failed on Apple Silicon - faking zero debug registers
[mvk-info] Created VkDevice to run on GPU Apple M1 with the following 1 Vulkan extensions enabled:
		VK_KHR_swapchain v70
rface v1
		VK_EXT_pipeline_creation_cache_control v3
		VK_EXT_post_depth_coverage v1
		VK_EXT_private_data v1
		VK_EXT_robustness2 v1
		VK_EXT_sample_locations v1
		VK_EXT_scalar_block_layout v1
		VK_EXT_separate_stencil_usage v1
		VK_EXT_shader_atomic_float v1
		VK_EXT_shader_stencil_export v1
		VK_EXT_shader_viewport_index_layer v1
		VK_EXT_subgroup_size_control v2
		VK_EXT_surface_maintenance1 v1
		VK_EXT_swapchain_colorspace v4
		VK_EXT_swapchain_maintenance1 v1
		VK_EXT_texel_buffer_alignment v1
		VK_EXT_texture_compression_astc_hdr v1
		VK_EXT_vertex_attribute_divisor v3
		VK_AMD_gpu_shader_half_float v2
		VK_AMD_negative_viewport_height v1
		VK_AMD_shader_image_load_store_lod v1
		VK_AMD_shader_trinary_minmax v1
		VK_IMG_format_pvrtc v1
		VK_INTEL_shader_integer_functions2 v1
		VK_GOOGLE_display_timing v1
		VK_MVK_macos_surface v3
		VK_MVK_moltenvk v37
		VK_NV_fragment_shader_barycentric v1
		VK_NV_glsl_shader v1
0374: thread_get_state failed on Apple Silicon - faking zero debug registers
038c: thread_get_state failed on Apple Silicon - faking zero debug registers
0398: thread_get_state failed on Apple Silicon - faking zero debug registers
0184: thread_get_state failed on Apple Silicon - faking zero debug registers
	VK_KHR_multiview v1
		VK_KHR_portability_subset v1
		VK_KHR_push_descriptor v2
		VK_KHR_relaxed_block_layout v1
		VK_KHR_sampler_mirror_clamp_to_edge v3
		VK_KHR_sampler_ycbcr_conversion v14
		VK_KHR_separate_depth_stencil_layouts v1
		VK_KHR_shader_draw_parameters v1
		VK_KHR_shader_float_controls v4
		VK_KHR_shader_float16_int8 v1
		VK_KHR_shader_subgroup_extended_types v1
		VK_KHR_spirv_1_4 v1
		VK_KHR_storage_buffer_storage_class v1
		VK_KHR_surface v25
		VK_KHR_swapchain v70
		VK_KHR_swapchain_mutable_format v1
		VK_KHR_timeline_semaphore v2
		VK_KHR_uniform_buffer_standard_layout v1
		VK_KHR_variable_pointers v1
		VK_EXT_buffer_device_address v2
		VK_EXT_debug_marker v4
		VK_EXT_debug_report v10
		VK_EXT_debug_utils v2
		VK_EXT_descriptor_indexing v2
		VK_EXT_external_memory_host v1
		VK_EXT_fragment_shader_interlock v1
		VK_EXT_hdr_metadata v2
		VK_EXT_host_query_reset v1
		VK_EXT_image_robustness v1
		VK_EXT_inline_uniform_block v1
		VK_EXT_memory_budget v1
		VK_EXT_metal_objects v1
		VK_EXT_metal_su[mvk-info] Created VkInstance for Vulkan version 1.1.0, as requested by app, with the following 2 Vulkan extensions enabled:
		VK_KHR_surface v25
		VK_EXT_metal_surface v1
0184: thread_get_state failed on Apple Silicon - faking zero debug registers
0184: thread_get_state failed on Apple Silicon - faking zero debug registers
03fc: thread_get_state failed on Apple Silicon - faking zero debug registers
041c: thread_get_state failed on Apple Silicon - faking zero debug registers
0448: thread_get_state failed on Apple Silicon - faking zero debug registers
02b4: thread_get_state failed on Apple Silicon - faking zero debug registers
0488: thread_get_state failed on Apple Silicon - faking zero debug registers
0498: thread_get_state failed on Apple Silicon - faking zero debug registers
0498: thread_get_state failed on Apple Silicon - faking zero debug registers
0184: thread_get_state failed on Apple Silicon - faking zero debug registers
0184: thread_get_state failed on Apple Silicon - faking zero debug registers
01cc: thread_get_state failed on Apple Silicon - faking zero debug registers
```

### What version of Whisky are you using?

1.0.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Try editing the Skyrim.ini similar to what's described here but the other way around https://steamcommunity.com/app/489830/discussions/0/3216031607507754305/

**Comment by frootloop88** [comment]
> Try editing the Skyrim.ini similar to what's described here but the other way around https://steamcommunity.com/app/489830/discussions/0/3216031607507754305/

what do you mean "the other way around"?
I tried with uiAudioHWThread=2 (because 2 speakers?" but it doesn't help

**Comment by IsaacMarovitz** [comment]
> I tried with uiAudioHWThread=2 (because 2 speakers?) but it doesn't help

2 should be the correct value. Are you sure the issue is cause it's in surround sound, or is it another issue?

**Comment by frootloop88** [comment]
> > I tried with uiAudioHWThread=2 (because 2 speakers?) but it doesn't help
> 
> 2 should be the correct value. Are you sure the issue is cause it's in surround sound, or is it another issue?

idk its the only thing that makes sense

**Comment by 556644O** [comment]
Same issue using GPTk ver.1.0.2. And I can confirm there is no NPC's sounds under GPTk ver.1.0.0. Maybe an update of GPTk can fix it.

**Comment by CaptainAmpersand** [comment]
Not sure how much this will help -- I see this from Codeweavers as the solution they came up with

I haven't tested it myself however I am experiencing the same issue (especially since I am not sure where to get these files)
https://www.codeweavers.com/compatibility/crossover/tips/the-elder-scrolls-v-skyrim-special-edition/fix-for-audio-issues

It says:
> If you can't hear any dialogue or the dialogue sounds messed up in any way, try adding these dll overrides:
> x3daudio1_6
> x3daudio1_7
> xaudio2_6
> xaudio2_6
> 
> To do this, locate to your Skyrim bottle and press Wine Configuration. Then go to the Libraries tab and type in the dlls mentioned above. Click Add. Be sure to set all of the to Native, Builtin. Click Apply then Ok.

**Comment by IsaacMarovitz** [comment]
You can add that as a env var set `WINEDLLOVERRIDES` to `x3daudio1_6,x3daudio1_7,xaudio2_6=n,b`

**Comment by frootloop88** [comment]
> env var set

how ecatbl

> You can add that as a env var set `WINEDLLOVERRIDES` to `x3daudio1_6,x3daudio1_7,xaudio2_6=n,b`. I don't have Skyrim but let me know if that works.

how exactly do I do that?

**Comment by frootloop88** [comment]
> Not sure how much this will help -- I see this from Codeweavers as the solution they came up with
> 
> I haven't tested it myself however I am experiencing the same issue (especially since I am not sure where to get these files) https://www.codeweavers.com/compatibility/crossover/tips/the-elder-scrolls-v-skyrim-special-edition/fix-for-audio-issues
> 
> It says:
> 
> > If you can't hear any dialogue or the dialogue sounds messed up in any way, try adding these dll overrides:
> > x3daudio1_6
> > x3daudio1_7
> > xaudio2_6
> > xaudio2_6
> > To do this, locate to your Skyrim bottle and press Wine Configuration. Then go to the Libraries tab and type in the dlls mentioned above. Click Add. Be sure to set all of the to Native, Builtin. Click Apply then Ok.
> > *Of course, we don't have a Libraries tab nor the dlls mentioned above, but most likely exist somewhere online

this is a fix for no npc/music audio at all not for the audio channel bug.

**Comment by CaptainAmpersand** [comment]
After a fair bit more testing on my end, you are absolutely correct, my apologies. It appeared as though that was the solution as they are using relatively the exact same setup, however I can confirm now first-hand that just that did not solve the problem.

@IsaacMarovitz Would you like a copy of Skyrim? Fun game and I know that when I downloaded Whisky it was my first game to test "if it works".

**Comment by IsaacMarovitz** [comment]
> @IsaacMarovitz Would you like a copy of Skyrim? Fun game and I know that when I downloaded Whisky it was my first game to test "if it works".

Donations are always welcome :D. Steam username is isaacryu

**Comment by IsaacMarovitz** [comment]
@CaptainAmpersand Friend request accepted

**Comment by frootloop88** [comment]
> @CaptainAmpersand Friend request accepted

did you find anything? :)

**Comment by CaptainAmpersand** [comment]
No such luck as of yet, but been trying to figure out in my free time. So far, experiencing the same issue. My solution has been to just talk *for* the NPCs, which is also hilarious

**Comment by IsaacMarovitz** [comment]
@CaptainAmpersand I received your gift 😄 should be able to do some testing tomorrow

**Comment by IsaacMarovitz** [comment]
Interestingly I ran into the bug where NPC dialogue cannot be heard at all...

**Comment by CaptainAmpersand** [comment]
My pleasure :)

That is the same issue I was facing as well, i kept reloading and hoping to hear, "Hey, you, you're finally awake"

**Comment by CaptainAmpersand** [comment]
Confirmed to still be present with latest version of Wine & GPTK 1 Beta 3

**Comment by dirkgroot** [comment]
From a quick test I did, it seems that installing `faudio` using winetricks fixes the NPC sounds.

Credits: https://github.com/Gcenx/WineskinServer/wiki/Skyrim-on-Apple-Silicon-with-Wineskin

**Comment by IsaacMarovitz** [comment]
Haven't been able to test myself yet, but I've added it to the Game Support wiki instructions

**Comment by IsaacMarovitz** [comment]
Seems to have some sampling rate problems but does in fact fix the NPC sounds.

**Comment by dirkgroot** [comment]
On the wiki, you warn that user interaction is required when performing the suggested winetricks command. Winetricks does, however, support the `-q` flag, which you can use to perform the command in unattended mode. It will still take a long time, but user interaction will not be necessary anymore.

You can put the `-q` flag at the beginning of the command.

**Comment by Notacod3r** [comment]
Is there any way to fix this issue on Whiskey? It seems Winetricks requires Wineskin which is its own separate thing from Whiskey.

**Comment by Notacod3r** [comment]
When doing the command `dotnet48 vcrun2019 dxvk1103 d3dx11_43 d3dcompiler_43 d3dcompiler_47 faudio` In the middle of the installation, the terminal shows: `Cannot find cabextract.  Please install it (e.g. 'sudo apt-get install 
cabextract' or 'sudo yum install cabextract')`

However, trying those install commands just gives me sudo: `apt-get: command not found.` Does anyone know a solution for this?

**Comment by KusStar** [comment]
> When doing the command `dotnet48 vcrun2019 dxvk1103 d3dx11_43 d3dcompiler_43 d3dcompiler_47 faudio` In the middle of the installation, the terminal shows: `Cannot find cabextract. Please install it (e.g. 'sudo apt-get install cabextract' or 'sudo yum install cabextract')`
> 
> However, trying those install commands just gives me `sudo: apt-get: command not found.` Does anyone know a solution for this?

You can just install with homebrew

```
brew install cabextract
```

**Comment by lv4n3yy** [comment]
So, did someone get the solution to no voices and music? I have tried almost all of that is written here and in other sources, but nothing helped me(Just maybe I did smth unproperly)

**Comment by AZavershinskiy** [comment]
Try it with Win7. I have normal voices now

**Comment by AZavershinskiy** [comment]
> > Try it with Win7. I have normal voices now
> 
> win 7 64 bit?

<img width="160" alt="Screenshot 2024-01-16 at 01 42 05" src="https://github.com/Whisky-App/Whisky/assets/107557520/5030673b-9709-48c1-8b11-7cb277f8783b">

<img width="827" alt="Screenshot 2024-01-16 at 01 43 10" src="https://github.com/Whisky-App/Whisky/assets/107557520/dd9c0e52-7e08-479b-9349-7e3cef138c3e">
