### ISSUE TITLE
[Bug]: Updated Steam is not launched & steam not loaded mf.dll

### ISSUE THREAD

**Issue by 97lily** [IsaacMarovitz/Whisky#237]
### Description

In the past, there was a phenomenon where nothing was displayed on the login screen on steam, but in my environment, even if both versions of GPT were installed and confirmed, the problem occurred that the dialog itself was not displayed. Also, I found some information that might be useful for finding a solution, so I will report it as well.

### Steps to reproduce

[installing]
1. installing steam like normaly,
2. close steam when finished update and close the not dialog steam from [kill bottle] from whisky menu
[error search]
1.click exexture on wiskey
2.well you opened dialog are show about drive_c folder 
3. firstly go select windows folder from on drive_c folder
4. goto syswow64 and click cmd.exe
5. now you launched cmd
6. use cd command and going c:¥program files(x86)¥steam like the screenshot
![type](https://github.com/IsaacMarovitz/Whisky/assets/33802452/b04d749e-a093-4b49-8580-d1d18df7c0df)

 7.type steam.exe in command, you canlaunch log in console 

![error](https://github.com/IsaacMarovitz/Whisky/assets/33802452/9e54196a-8f30-4753-b2c6-559a4559bd03)

[logs]
finally im checked some error is happened in process

![名称未設定](https://github.com/IsaacMarovitz/Whisky/assets/33802452/dd3b095e-8d3e-4ea0-8153-b1a44fffc95d)

note:If the dialog is left undisplayed, the following error log is output (although it is a repeating format...)
![testy](https://github.com/IsaacMarovitz/Whisky/assets/33802452/aa29bc4c-ea6a-4de6-854d-11864c71e46e)

In the error displayed in the second dialog, you can see that it is looping due to an error loading mf.dll.

### Expected behaviour

The steam window should display normally

### Logs

```bash
im uploaded console error on Step section
(because wine default terminal is can'not copy texts)
[detail on log
In this place, I will write about two factors that seem to be the cause

1.wine(or steam or gpt engine) failed to loading mf.dll
3.steamhelper doesn't launching from the issue
```

### What version of Whisky are you using?

1.0.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by K0K1-0928** [comment]
Does the font relationship look OK?
I can see Japanese in the log you pasted, so I have a feeling it is similar to the problem I have encountered.
#179

**Comment by TRSasasusu** [comment]
I've encountered this problem, but it is solved:

1. delete the bottle
2. change the default language to English of the Mac:  
<img width="714" alt="image" src="https://github.com/IsaacMarovitz/Whisky/assets/17728957/414c7073-f146-4b3b-bb39-eb67c12d3890">

3. create a bottle, and install Steam with language as English
4. Steam launched

Our error log says `mf.dll` related error, but above solution works in my environment.
