### ISSUE TITLE
[Feature]: Enable Microphone Use for Games

### ISSUE THREAD

**Issue by millzanz** [IsaacMarovitz/Whisky#239]
### Is your feature request related to a problem?

When playing Diablo 4 the Microphone is not available when using the Whisky implementation.  When using the GPTK via Apple's instructions I am able to use the microphone as terminal is a listed application.

### Describe the solution you'd like

Whisky to be listed in the Microphone allowed section of the privacy and security section of system settings.

### Anything else?

<img width="497" alt="Screenshot 2023-07-13 at 6 25 03 AM" src="https://github.com/IsaacMarovitz/Whisky/assets/8346707/666a0ac7-2adb-4de7-a99c-fc362f4e65cd">

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Should be a simple permissions change 👍
