### ISSUE TITLE
[Bug] Skyrim SE doesn't start

### ISSUE THREAD

**Issue by VictoriousOpossum** [IsaacMarovitz/Whisky#241]
Thank you for the fantastic app! 

**Machine**

MacBook Pro, M1, 2020, macOS Sonoma 14.0 Beta (23A5286i). Apple's game Porting Kit is installed.

**Issue**

1. Created a bottle for Steam
2. Installed Skyrim SE
3. Upon launch, I see a preview of Bethesda (Skyrim) launcher, but Wine closes the app with "a serious problem".

Thank you for your work and help!

**Dubug summary from ChatGPT**

> The error message indicates that an unhandled exception occurred in the program "skyrimselauncher". The exception is a page fault on a read access operation to memory address 0x0000000000000000. 

> Here is a breakdown of the error message:
> 
> - Exception type: Page fault on read access
> - Memory address: 0x0000000000000000
> - Program name: skyrimselauncher
> - Register dump: Shows the values of various registers at the time of the exception
> - Stack dump: Shows the contents of the stack memory at the time of the exception
> - Backtrace: Provides information about the function call stack leading up to the exception
> 
> The error suggests that the program attempted to read from a memory address that is not valid or accessible, specifically address 0x0000000000000000. This could be due to a null pointer dereference, where the program tried to access data through a null pointer.
> 
> To further diagnose and resolve the issue, it would be helpful to have more information about the context in which the error occurred, such as the steps leading up to the error, the operating system and version being used, and any relevant software or libraries involved.

**Debug**

`Unhandled exception: page fault on read access to 0x0000000000000000 in 64-bit code (0x00000140006bb1).
Register dump:
 rip:0000000140006bb1 rsp:000000000011f400 rbp:000000000011f9d0 eflags:00000202 (   - --  I   - - - )
 rax:00003115de552944 rbx:000000000011f988 rcx:0000000000000000 rdx:0000000000000000
 rsi:0000000000000001 rdi:0000000000000000  r8:000000023d8d67d0  r9:000000023d8d64c0 r10:00000000c0000001
 r11:000000017006ba60 r12:0000000000000000 r13:0000000000000000 r14:000000000025a13b r15:0000000140000000
Stack dump:
0x0000000011f400:  005000730077006f 007200650077006f
0x0000000011f410:  006c006500680073 00310076005c006c
0x0000000011f420:  0070005c00000000 fffffffffffffffe
0x0000000011f430:  000000000011f988 0065007000530020
0x0000000011f440:  006c006100690063 0000000000266e20
0x0000000011f450:  000000000011f5a0 0000000170066490
0x0000000011f460:  000000000011f860 000000017004e819
0x0000000011f470:  000000000000006c 000000000011f620
0x0000000011f480:  000000000011f510 000000017002dac3
0x0000000011f490:  0000000000000001 0000000170065450
0x0000000011f4a0:  0000000000000202 000000017002d470
0x0000000011f4b0:  000000000011f490 0000000327020000
Backtrace:
=>0 0x00000140006bb1 in skyrimselauncher (+0x6bb1) (0x0000000011f9d0)
  1 0x00000140008d19 in skyrimselauncher (+0x8d19) (0x0000000011f9d0)
  2 0x00000140008c3d in skyrimselauncher (+0x8c3d) (0x0000000011fc99)
  3 0x00000140006995 in skyrimselauncher (+0x6995) (0x0000000011fd99)
  4 0x00000140013d8a in skyrimselauncher (+0x13d8a) (0000000000000000)
  5 0x0000007b62a889 BaseThreadInitThunk+0x9(unknown=<internal error>, entry=<internal error>, arg=<internal error>) [Z:\private\tmp\game-porting-toolkit-20230713-41927-mohr5u\wine\dlls\kernel32\thread.c:61] in kernel32 (0000000000000000)
  6 0x0000017005b3b8 __wine_pop_frame(unknown=<internal error>, entry=<internal error>, arg=<internal error>) [Z:\private\tmp\game-porting-toolkit-20230713-41927-mohr5u\wine\include\wine\exception.h:275] in ntdll (0000000000000000)
  7 0x0000017005b3b8 RtlUserThreadStart+0x88(entry=[<register RSP not accessible in this frame>, arg=[<register RSP not accessible in this frame>) [Z:\private\tmp\game-porting-toolkit-20230713-41927-mohr5u\wine\dlls\ntdll\thread.c:240] in ntdll (0000000000000000)
0x00000140006bb1 skyrimselauncher+0x6bb1: movq	(%rcx),%rax
Modules:
Module	Address					Debug info	Name (32 modules)
PE	0000000001470000-0000000001481000	Deferred        psapi
PE	0000000002d00000-0000000002fd4000	Deferred        d3d9
PE	0000000068870000-0000000068873000	Deferred        win32u
PE	000000006aea0000-000000006aea6000	Deferred        winemac
PE	000000007b000000-000000007b558000	Deferred        kernelbase
PE	000000007b600000-000000007b7a4000	Dwarf-4-5       kernel32
PE	0000000140000000-0000000140480000	Export          skyrimselauncher
PE	0000000170000000-0000000170333000	Dwarf-4-5       ntdll
PE	0000000180000000-000000018018a000	Deferred        gameoverlayrenderer64
PE	00000001c69e0000-00000001c7768000	Deferred        shell32
PE	00000001c8b40000-00000001c8bb8000	Deferred        msacm32
PE	00000001c8db0000-00000001c90c6000	Deferred        msvcrt
PE	0000000231ae0000-0000000231d70000	Deferred        rpcrt4
PE	0000000236df0000-0000000236f53000	Deferred        dsound
PE	000000023d820000-000000023deff000	Deferred        user32
PE	000000026b4c0000-000000026b756000	Deferred        gdi32
PE	000000026ed50000-000000026ed67000	Deferred        vcruntime140
PE	00000002739c0000-0000000273ea5000	Deferred        oleaut32
PE	00000002bb750000-00000002bbca6000	Deferred        comctl32
PE	00000002e3540000-00000002e3656000	Deferred        shlwapi
PE	00000002e8f10000-00000002e9495000	Deferred        ole32
PE	00000002f1fa0000-00000002f1fc0000	Deferred        version
PE	00000002f7230000-00000002f72f0000	Deferred        uxtheme
PE	00000003126f0000-0000000312745000	Deferred        shcore
PE	0000000327020000-00000003271af000	Deferred        combase
PE	000000032a700000-000000032a7c0000	Deferred        sechost
PE	0000000330260000-000000033038e000	Deferred        advapi32
PE	0000000360e10000-0000000360ead000	Deferred        msvcp140
PE	00000003871c0000-0000000387211000	Deferred        concrt140
PE	00000003af670000-00000003af9f8000	Deferred        ucrtbase
PE	00000003afd00000-00000003afd66000	Deferred        imm32
PE	00000003b8f00000-00000003b90b9000	Deferred        winmm
Threads:
process  tid      prio    name (all IDs are in hex)
00000030 services.exe
	00000034    0     
	00000038    0     
	00000044    0     
	00000080    0     
	000000a4    0     
	000000bc    0     
	000000f8    0     
0000003c winedevice.exe
	00000040    0     
	0000004c    0     
	00000050    0     
	00000054    0     
	00000058    0     
	000000c8    0     
00000078 winedevice.exe
	0000007c    0     
	00000084    0     
	00000088    0     
	0000008c    0     
	00000090    0     
	00000094    0     
	00000098    0     
0000009c plugplay.exe
	000000a0    0     
	000000a8    0     
	000000ac    0     
	000000b0    0     
	00000134    0     
	00000138    0     
	000001f0    0     
	000001f4    0     
000000b4 svchost.exe
	000000b8    0     
	000000c0    0     
	000000c4    0     
000000d4 steam.exe
	000000d8    0     
	00000114    0     
	00000118    0     
	00000120    0     
	00000128    0     
	0000012c    0     
	00000130    0     
	00000144    0     
	00000148    0     
	00000150    0     
	00000164    0     
	00000168    0     
	00000170    0     
	00000178    0     
	0000017c    0     
	00000180    2     
	00000184    2     
	0000018c    0     
	00000190    0     
	00000194    0     
	00000208    0     
	0000020c    0     
	00000210    0     
	0000021c    0     
	00000220    2     
	00000224    0     
	00000234    0     
	00000240    0     
	00000244    0     
	00000308    0     
	00000314    0     
	00000338    0     
	0000033c    0     
	00000344    0     
	00000358    0     
	0000048c    0     
	00000564    0     
000000dc explorer.exe
	000000e0    0     
	000000e4    0     
	000000e8    0     
000000f0 rpcss.exe
	000000f4    0     
	000000fc    0     
	00000100    0     
	00000104    0     
	00000108    0     
	0000010c    0     
	00000328    0     
	00000350    0     
0000013c steamwebhelper.exe
	00000140    0     
	00000154    0     
	00000158    0     
	0000019c    0     
	000001a0    0     
	000001a4    0     
	000001a8   -2     
	000001ac    0     
	000001b0    0     
	000001b4    0     
	000001b8    0     
	000001bc    0     
	000001c0    0     
	000001d0    0     
	000001d4    1     
	000001d8    0     
	000001dc    0     
	000001e0    0     
	000001e4    1     
	000001e8    0     
	000001ec    0     
	000001f8   -2     
	000001fc    0     
	00000200    0     
	00000228    0     
	00000248    0     
	00000324    0     
00000238 steamwebhelper.exe
	0000023c    0     
	00000254    0     
	00000258    0     
	00000260   -2     
	00000264    0     
	00000268    0     
	0000026c    0     
	00000274    0     
	000002f4    0     
0000024c steamwebhelper.exe
	00000250    0     
	00000288    0     
	0000028c    0     
	00000294   -2     
	00000298    1     
	0000029c    0     
	000002a0    0     
	000002a4    0     
	000002a8    1     
	000002ac    0     
	000002b0    0     
	000002b4    0     
	000002b8    0     
	000002bc    0     
	000002c0   -2     
	000002dc    0     
	0000034c    0     
	00000544    0     
	00000550    1     
	00000554    0     
	000005bc    0     
0000037c steamwebhelper.exe
	00000380    0     
	000003d0    0     
	000003d4    0     
	000003dc   -2     
	000003e0    1     
	000003e4    0     
	000003e8    0     
	000003ec    0     
	000003f0    1     
	000003f4    0     
	000003f8    0     
	000003fc    0     
	00000400    0     
	00000404    0     
	00000408   -2     
	000005b0    0     
00000410 steamwebhelper.exe
	00000414    0     
	00000424    0     
	00000428    0     
	00000430   -2     
	00000434    1     
	00000438    0     
	0000043c    0     
	00000440    0     
	00000444    1     
	00000448    0     
	0000044c    0     
	00000450    0     
	00000454    0     
	00000458    0     
	0000045c   -2     
	00000484    0     
	000005c4    0     
	000005c8    0     
	000005cc    0     
	000005d0    0     
	000005d4    0     
	000005d8    0     
00000514 steamwebhelper.exe
	00000518    0     
	0000051c    0     
	00000520    0     
	00000524    0     
	00000528   -2     
	0000052c    0     
	00000530    0     
	00000534    0     
	0000053c    0     
	00000540    0     
	000005c0    0     
00000570 (D) C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\SkyrimSELauncher.exe
	00000574    0 <== 
	00000594    0     
00000588 conhost.exe
	0000058c    0     
System information:
    Wine build: wine-7.7
    Platform: x86_64
    Version: Windows 10
    Host system: Darwin
    Host version: 23.0.0
`

**Comment by IsaacMarovitz** [comment]
Please see the [wiki](https://github.com/IsaacMarovitz/Whisky/wiki/Game-Support#skyrim-se---has-audio-problems)
