### ISSUE TITLE
What‘s the difference between GPTK from Apple and Whisky?

### ISSUE THREAD

**Issue by tyIceStream** [IsaacMarovitz/Whisky#243]
Hi,
In the README from GPTK, we should use `brew  install game-porting-toolkit` to install the game-porting-toolkit library, it compiles and consumes lots of time. But in the Whisky, we don't need to run this.
Any difference here? I want to know if it there's gap on performance or something else? Does the toolkit from Apple have higher performance in game?

**Comment by CMMChris** [comment]
GPTK and Whisky are literally the same thing. Whisky is just a GUI for GPTK and bundles a pre-built Wine environment so you don't have to spend time compiling all the stuff. In terms of functionality and performance, there isn't any difference.

**Comment by tyIceStream** [comment]
Hi @CMMChris , thanks for your answer.
I find that the game-porting-toolkit depends on the source of crossover when Whisky uses wine as backend. That may be something different.
And I heard from my friends that the performance of Whisky is lower than GPTK when running some games.

**Comment by CMMChris** [comment]
It doesn't matter what your friends say and you obviously don't know what you are talking about. Whisky uses the same Crossover Base as GPTK since GPTK relies on code changes within that CX base.

**Comment by MisutaaAsriel** [comment]
> I find that the game-porting-toolkit depends on the source of crossover when Whisky uses wine as backend. That may be something different.

@tyIceStream Crossover **is** WINE. Codeweavers is the development team behind Crossover, a commercial WINE package, and they are a **major** contributor to the WINE project. Their fork of WINE is open source, and both GPTK, & Whisky use that as a base.

`brew -v install apple/apple/game-porting-toolkit` isn't installing *the full* game porting toolkit, but rather, mostly, WINE. For whatever reason, the GPTK currently distributes its binaries and WINE enhancements on a DMG (which you drag into Whisky), and WINE itself via `brew`.

When you launch Whisky for the first time, it downloads the same Crossover-fork of WINE, then has you drag-and-drop the latest GPTK DMG to add it on top and configure.

In short, Whisky is doing the same thing the instructions are, but in a more user friendly way, and removing any of the hassle of setup that may be needed when doing it yourself.

> And I heard from my friends that the performance of Whisky is lower than GPTK when running some games.

**For what its worth, Whisky is the only one to run Expression Design 4 for me**, so what it does in terms of configuration shan't be overlooked. — I was struggling to get it configured properly, even when using the GPTK from the command line. So something about how Whisky launches and preconfigures the WINE environment seems more conducive to functionality in my experience.

With any version of WINE, Linux or Mac, it's *all about the configuration*. WINE isn't like Windows where it's a specific version of Windows running specific versions of DLLs. It has the ability to *simulate* multiple versions of Windows, and its "out of the box" configuration can be pretty bare bones. Often, configuration of the WINE environment *will be down to the specific program*. So any performance or stability issues between the two will be down to how the environment is configured.
