### ISSUE TITLE
[Bug]: Mass Effect Andromeda - EA app

### ISSUE THREAD

**Issue by woile** [IsaacMarovitz/Whisky#246]
### Description

EAapp cannot be installed

### Steps to reproduce

I've been trying to play Mass Effect andromeda using Steam, Steams seems to attempt to install `EaApp.exe`. Which opens a screen 

<img width="484" alt="Screenshot 2023-07-15 at 08 12 01" src="https://github.com/IsaacMarovitz/Whisky/assets/2585816/2fe1ae9e-e9b4-4de0-a2a2-36aba60bfb05">

When clicking on Let's go, it looks like it's doing something but in the end we get an error symbol, with an 'ok' button, no information displayed. The button "customize setup" doesn't work

<img width="484" alt="Screenshot 2023-07-15 at 08 13 13" src="https://github.com/IsaacMarovitz/Whisky/assets/2585816/24303605-10b9-4ee4-a903-29cd9eeff525">

I think this prevents the game from launching.

I've tried downloading directly the EA App and installing it https://www.ea.com/ea-app
but I get the same error

### Expected behaviour

Steam should be able to install EA app

### Logs

```bash
I don't know how to collect logs for this app
```

### What version of Whisky are you using?

1.0.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

### Resources

I've collected some resoruces that may help:

- https://appdb.winehq.org/objectManager.php?sClass=version&iId=41337
- https://github.com/kageurufu/steamdeck-tricks/blob/main/ea-app.md

**Comment by mavethee** [comment]
And it won't work unless GPTK will use Wine 8.0.1 with Codeweavers hacks in ntdll.

**Comment by Crd5** [comment]
> And it won't work unless GPTK will use Wine 8.0.1 with Codeweavers hacks in ntdll.

What are Codeweavers hacks?

**Comment by Crd5** [comment]
> And it won't work unless GPTK will use Wine 8.0.1 with Codeweavers hacks in ntdll.

So, what version of wine is required?

**Comment by IsaacMarovitz** [comment]
EA app is a PITA to get working in Wine. The usual workaround for EA is to install Origin instead or check if the game installs a DRM/EA-free version like Fallen Order does. I don't have the game, so I'm unable to check myself.

**Comment by woile** [comment]
I couldn't find the origin installer. It redirects me to the ea app. Any idea where to find it?

**Comment by Crd5** [comment]
Origin can be installed into crossover. I think it would work in Whiskey, too. I played Star Wars Battlefront II using crossover 21.1 (How I remember) via Origin, but you need to edit local.xml to skip ea app update (https://www.reddit.com/r/origin/comments/11g6qrf/how_to_actually_bypass_the_forced_ea_app_install/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=2). I will try it again in Whiskey later

**Comment by captain0305** [comment]
> Origin can be installed into crossover. I think it would work in Whisky, too. I played Star Wars Battlefront II using crossover 21.1 (How I remember) via Origin, but you need to edit local.xml to skip ea app update (https://www.reddit.com/r/origin/comments/11g6qrf/how_to_actually_bypass_the_forced_ea_app_install/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=2). I will try it again in Whisky later

hey dude,  did you succeed in install ea app via steam using Whisky? I met this issue now. It just can't be installed via steam and no log like this
<img width="1400" alt="image" src="https://github.com/Whisky-App/Whisky/assets/63387697/9306b669-2ce3-4587-ad9e-7c1ff0a7a9eb">

**Comment by BingliangLi** [comment]
In crossover, by enabling the high resolution mode I managed to get the EA App work, haven't try it on Whisky though.

**Comment by mavethee** [comment]
Whisky is based on GPTK 1.1, GPTK alone without latest CrossOver changes will not work with EA App.
If Apple will decide to rely on newer Wine than 7.7, it will be fixed.
All that was mentioned in 1st comment already.

Only workaround is to use this if still works:
https://github.com/p0358/Fuck_off_EA_App
