### ISSUE TITLE
Steam won't open

### ISSUE THREAD

**Issue by matvada** [IsaacMarovitz/Whisky#247]
Hello, 
Steam stopped working...

The Steam update popup opens but the program doesn't launch once it's done.
I'm on Whiskey 1.0.1
Sonoma beta 3 

Environment Variables on Steam:
WINEDLLOVERRIDES dxgi,d3d9,d3d10core,d3d11=b

Thanks

**Comment by Yuuki-Sakura** [comment]
same problem

steam cef_log:
```
[0715/143825.484:INFO:crash_reporting.cc(248)] Crash reporting enabled for process: browser
[0715/143825.884:ERROR:network_change_notifier_win.cc(142)] WSALookupServiceBegin failed with: 0
[0715/143826.035:ERROR:dxva_video_decode_accelerator_win.cc(1338)] DXVAVDA fatal error: Could not load mf.dll: 找不到模块。 (0x7E)
[0715/143827.081:ERROR:platform_font_skia.cc(343)] Could not find any font: MS Shell Dlg, sans. Falling back to the default
```

**Comment by chenxi050402** [comment]
same problem and looks like the same issue as #237

**Comment by woile** [comment]
I've been able to open it by changing the windows version, no idea why it works

**Comment by matvada** [comment]
@woile what version of windows did you set?

Thanks

**Comment by woile** [comment]
I swap between 7 and 10.
Change to 7, open steam. Next time change to 10 and open steam. No idea if it works on other machines, but seems to work in mine

**Comment by thisisWuRan** [comment]
still cannot open :(

**Comment by peace1010** [comment]
I had the same problem,
 but I've been able to open it  by completely deleting the bottle that contains Steam
Then I created a new bottle, added Steam, ran it, then it started updating and finally opened normally.

**Comment by farrukitojajajaj** [comment]
For everyone that can't run steam because the botton won't work:

All you have to do is uninstall complete Whisky app from ur Mac and also Steam. After that install whisky and the steam.exe and do the process, it should work.

To uninstall correctly both apps use: AppCleaner that will eliminate all the files related to these apps.
