### ISSUE TITLE
Drag and Drop dmg

### ISSUE THREAD

**Issue by l0stl0rd** [IsaacMarovitz/Whisky#25]
Does not work for me it keeps showing up.
When I copy the files manually it is fine.

**Comment by Jepl4r** [comment]
For me it showed up only two times. Dropped the DMG and now it doesn't ask for it anymore. Try uninstalling the app with App Cleaner (https://freemacsoft.net/appcleaner/) and reinstall it.

**Comment by IsaacMarovitz** [comment]
Should be fixed by #36
