### ISSUE TITLE
[Bug]: Whisky not saving imported bottles

### ISSUE THREAD

**Issue by redeemer666** [IsaacMarovitz/Whisky#255]
### Description

Whisky does not save bottles created by external tool

### Steps to reproduce

If you try to import a bottle (I have them on my home folder) then you close and reopen the program the bottles have disappeared

### Expected behaviour

It should save them

### Logs

```bash
No logs
```

### What version of Whisky are you using?

1.0.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Madoc439** [comment]
This is now true in 1.1.0(17).  Creating a new bottle nor importing a created bottle works.  I have no bottles nor can have any.

**Comment by newkincode** [comment]
When you create a bottle, it appears and disappears.
