### ISSUE TITLE
How to install and run Whisky

### ISSUE THREAD

**Issue by johnsolo112** [IsaacMarovitz/Whisky#26]
Hi,
I’m a complete beginner, how do I go about installing and running Whisky?

**Comment by rhysm94** [comment]
Go to the Releases section and download Whisky.zip
Move the file to Applications if you want
Run the Whisky app

**Comment by cristaloleg** [comment]
Hey, I have a question regarding this line:

> Drag and drop the contents of the game porting toolkit's lib folder into the `Wine` folder and select Merge

especially:
> into the `Wine` folder and select Merge.

What is the `Wine` folder? What do you mean by that?

CC: @IsaacMarovitz

**Comment by runkaiz** [comment]
I believe the latest version now has a feature that lets you drag and drop the GPT's dmg file and it will merge the contents for you. That being said there is not a lot of documentations right now and frankly I haven't gotten it to work myself.
