### ISSUE TITLE
[Bug]: Bottle name isnt correct

### ISSUE THREAD

**Issue by Crd5** [IsaacMarovitz/Whisky#263]
### Description

When I create a bottle, the bottle gets a strange name. 
<img width="1032" alt="Снимок экрана 2023-07-25 в 15 08 31" src="https://github.com/IsaacMarovitz/Whisky/assets/62203291/720ab477-8bb5-4ba5-9e61-bd9cdb09ebe8">

<img width="1346" alt="Снимок экрана 2023-07-25 в 15 06 54" src="https://github.com/IsaacMarovitz/Whisky/assets/62203291/4f3853de-520c-45cc-83b5-2fea6d543ccc">

### Steps to reproduce

Just create a bottle

### Expected behaviour

How to fix it?

### Logs

```bash
No needed
```

### What version of Whisky are you using?

1.0.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Mika412** [comment]
Seems right to me. It's using a UUID for the folder name and stores the real bottle name in a config file. This way you can have multiple bottles with the same name, but with unique UUIDs.

**Comment by Crd5** [comment]
Yeah, but when 1.0.1 was just released there wasnt that
<img width="1346" alt="Снимок экрана 2023-07-26 в 12 52 23" src="https://github.com/IsaacMarovitz/Whisky/assets/62203291/95533d65-a8c2-4460-899e-5f377166e868">
