### ISSUE TITLE
[Feature]: Use `brew` provided wine-stable

### ISSUE THREAD

**Issue by LukeDRussell** [IsaacMarovitz/Whisky#265]
### Is your feature request related to a problem?

It seems many problems running particular applications are solved by updating `wine`. The bundled version Whisky downloads is 7.x, but 8.0 is available on homebrew.

I'm new to the Wine space, so I can't say for certain this would solve my particular problem. I'm currently unable to get Dwarf Fortress working (Steam version, v50).

### Describe the solution you'd like

It would be nice if Whisky would depend on the homebrew provided `wine-stable` (currently 8.0.x). As an alternative, could you bump the wine version downloaded and internalised by Whisky?

### Anything else?

No other suggestion. Love your work.

### Issue Language

- [X] Yes my issue is written in English

**Comment by LukeDRussell** [comment]
This may duplicate the closed #250.

**Comment by Crd5** [comment]
> This may duplicate the closed #250.

Closed but not solved

**Comment by LukeDRussell** [comment]
I've got Dwarf Fortress (Steam version) working by upgrading the game to 50.08 Beta. The developers are doing work to go from "SDL" to "SDL2", which apparently enables native Linux and MacOS game clients at some point in the future.

I still think this Issue is valid though, so I'll keep it open.

**Comment by tyIceStream** [comment]
This issue may helps you on it. https://github.com/IsaacMarovitz/Whisky/issues/207

**Comment by LukeDRussell** [comment]
Closing, as Wine is a version locked dependency.
