### ISSUE TITLE
[Bug]: Elite Dangerous Launch

### ISSUE THREAD

**Issue by johancedaniel** [IsaacMarovitz/Whisky#281]
### Description

The game does not launch
<img width="983" alt="Screenshot 2023-07-30 at 4 17 56 PM" src="https://github.com/IsaacMarovitz/Whisky/assets/102495052/26f1b6fd-9963-4fc6-9267-b81437535315">

### Steps to reproduce

Launch with steam

### Expected behaviour

The game is supposed to launch by showing the ED Launcher

### Logs

```bash
I dont know how to get this
```

### What version of Whisky are you using?

1.1.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Crd5** [comment]
I found [this guide](https://forums.frontier.co.uk/threads/how-to-play-elite-dangerous-on-mac-a-guide-by-kyle-krein.568064/) at [applegamingwiki](https://www.applegamingwiki.com/wiki/Elite:_Dangerous). 
1) Install [DirectX for modern games](https://files.holarse-linuxgaming.de/mirrors/microsoft/directx_Jun2010_redist.exe)
2) Enable DXVK in "config"
3) Install [.Net Framework 4.5.1](http://download.microsoft.com/download/1/6/7/167F0D79-9317-48AE-AEDB-17120579F8E2/NDP451-KB2858728-x86-x64-AllOS-ENU.exe)

P.S. I haven't played this game just found a guide in applegamingwiki

**Comment by johancedaniel** [comment]
i tried this but it does not work, also I tried the same with Whisky, Crossover plain and crossover gptk. None of them launch. Could i be because I am on Sonoma or is it because of the updates to the launcher from ED

**Comment by Crd5** [comment]
Have you Googled your error? It's Unity error. I think only game support can help you

**Comment by IsaacMarovitz** [comment]
As shown in the Wiki, Elite Dangerous is not currently working.

**Comment by Raq-3773** [comment]
I have got the same issue, i was playing with "advanced settings" for steam in Crossover, and after checking D3Dmetal i got an other code: (22708352). 
<img width="293" alt="Screenshot 2023-10-20 at 19 10 13" src="https://github.com/Whisky-App/Whisky/assets/110932182/424efea4-5800-4f2b-93c6-0821b08dbbf5">

I know Sonoma introduced problems for Discord and launching them in Rosetta salved that issue. Perhaps there is something there?

**Comment by mmangione** [comment]
Follow the updated guide here:
https://github.com/Whisky-App/Whisky/wiki/Game-Support#elite-dangerous

The problem is .Net. GPTK doesn't support it. So you need to use the minimal ED launcher to circumvent it.
