### ISSUE TITLE
how do I add a shortcut?

### ISSUE THREAD

**Issue by pallazola** [IsaacMarovitz/Whisky#283]
### Is your feature request related to a problem?

no

### Describe the solution you'd like

a plus button to add a shortcut, and run it from Home or the bottle

### Anything else?

I currently have two identical steams

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
You can already favourite applications from the Programs List. They will then appear on your main bottle view. Duplicate shortcuts can be removed by right-clicking and deleting them.

**Comment by pallazola** [comment]
yes, sorry I wasn't clear in my issue. How do I add a shortcut to an app not in the program list. It's an game installed by steam, but won't work when launched by steam, but will run when I run it directly.

**Comment by pallazola** [comment]
> Try to add program to desktop (C:\Users\yourusername\desktop)

tried that, didn't work :(

**Comment by pallazola** [comment]
ok I was able to add the Shortcut by opening explorer.exe, navigating to the .exe, right clicking and click Create Link. It shows up! but when I try to run it I get the "Failed to open program!" error. I look at the info for the shortcut and I see the path has a leading \ before the drive letter: "\F:\SteamLibrary...". If I look at other short cuts there is no leading slash \. see attached photos

leading slash:
<img width="541" alt="Screenshot 2023-08-19 at 4 36 08 PM" src="https://github.com/IsaacMarovitz/Whisky/assets/18120711/bd7d69fa-368f-4143-a249-9029c8bd61a5">
no leading slash:
<img width="538" alt="Screenshot 2023-08-19 at 4 35 52 PM" src="https://github.com/IsaacMarovitz/Whisky/assets/18120711/ab4d9a90-70c7-42ad-8209-6649937652bc">

Is it posible to edit the path?
