### ISSUE TITLE
三国志战略版无法运行error

### ISSUE THREAD

**Issue by 191338780** [IsaacMarovitz/Whisky#284]
Whisky Version: 1.1.0
Date: 2023/8/4 22:53:27
macOS Version: 版本14.0（版号23A5301h）
Bottle Name: sgz
Wine Version: 7.7.0
Wine Binary Version: 5
Windows Version: win10
Bottle URL: /Users/leo/Whisky/36F1A85C-FCF8-42C2-86BF-779CF35A127F

Arguments: start /unix /Users/leo/Whisky/36F1A85C-FCF8-42C2-86BF-779CF35A127F/drive_c/Program Files (x86)/sgzzlb/S3Client.exe 

Launched Wine (16389)
0068:err:module:open_builtin_so_file failed to load .so lib "/Users/leo/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/Wine/lib/wine/x86_64-unix/wineusb.sys.so"
0068:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
00d8: thread_get_state failed on Apple Silicon - faking zero debug registers
00d8: thread_get_state failed on Apple Silicon - faking zero debug registers
00d8: thread_get_state failed on Apple Silicon - faking zero debug registers
00d8: thread_get_state failed on Apple Silicon - faking zero debug registers
00d8:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
0184: thread_get_state failed on Apple Silicon - faking zero debug registers
01c4: thread_get_state failed on Apple Silicon - faking zero debug registers
00d8: thread_get_state failed on Apple Silicon - faking zero debug registers
Process exited with code 0

**Comment by NuclearKookaburra** [comment]
Hey, @191338780 👋 

To submit a bug, please, make sure to use [the template](https://github.com/IsaacMarovitz/Whisky/blob/main/.github/ISSUE_TEMPLATE/bug.yml) that the maintainer specified for it. Thanks!
