### ISSUE TITLE
[Bug]: New bottle on external ssd disappears as soon as it's created

### ISSUE THREAD

**Issue by d80h4g** [IsaacMarovitz/Whisky#286]
### Description

When I try to create a new bottle on an external disk, the bottle disappears as soon as it has been created. Bottle creates OK if created to default location in ~/Library.

I've enabled whole disk access for Whisky and this has not resolved the issued.

I've tried a couple of different files system for the external disk (APFS & exFAT) and still the same issue.

### Steps to reproduce

Click + for new bottle
Set location as folder in external disk
Click create
Cogs turns, folder is created on the external disk with Wine data, however the bottle immediately disappears from Whisky side pane.

### Expected behaviour

Bottle remains in Whisky side pane after it's been created.

### Logs

```bash
Whisky Version: 1.1.0
Date: 04/08/2023, 17:51:59
macOS Version: Version 14.0 (Build 23A5286i)
Bottle Name: steam-t7
Wine Version: 7.7.0
Wine Binary Version: 5
Windows Version: win10
Bottle URL: /Volumes/Samsung T7/Whisky Bottles/5E6A1D22-0EF4-4106-AD5C-EF0C7698F201

Arguments: winecfg -v win10 

Launched Wine (1088)
00f0: thread_get_state failed on Apple Silicon - faking zero debug registers
00f8: thread_get_state failed on Apple Silicon - faking zero debug registers
wine: configuration in L"/Volumes/Samsung T7/Whisky Bottles/5E6A1D22-0EF4-4106-AD5C-EF0C7698F201" has been updated.
Process exited with code 0
```

### What version of Whisky are you using?

1.1.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ae0n** [comment]
I was able to fix that by removing spaces from my ssd's name and as I see your drive have a space in the name

**Comment by d80h4g** [comment]
That fixed it. Thanks!

**Comment by ae0n** [comment]
@d80h4g but the bug is exist, it's just a temporary solution
