### ISSUE TITLE
[Bug]: Upgrading version shows Wine & GPTK not installed; Wine stuck at Zero KB of Zero KB downloading

### ISSUE THREAD

**Issue by sooheon** [IsaacMarovitz/Whisky#288]
### Description

Like title, when upgrading from 1.0.1 to 1.1.0, it prompts to reinstall libraries. The "Downloading Wine" modal will show zero progress, just "Zero KB of Zero KB"

### Steps to reproduce

After installing and using 1.0.1, replace the app with new download of 1.1.0. Opening app will prompt to redownload libs.

### Expected behaviour

Already downloaded libs should be preserved across upgrades. New downloads should work.

### Logs

```bash
App is stuck on download screen, no logs are generated.
```

### What version of Whisky are you using?

1.1.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Crd5** [comment]
Try to reinstall Whisky

**Comment by Traace** [comment]
I do think this is in fact a Whisky issue not a bad install or network issue. Getting 404 from webserver as return while trying to download wine.

CFNetwork:
```
Task <CE5730E7-37EF-4A6D-A813-DA7110B30D27>.<1> sent request, body N 0
Task <CE5730E7-37EF-4A6D-A813-DA7110B30D27>.<1> received response, status 404 content K
Task <CE5730E7-37EF-4A6D-A813-DA7110B30D27>.<1> done using Connection 1
```

Task Summary:
`Task <CE5730E7-37EF-4A6D-A813-DA7110B30D27>.<1> summary for task success {transaction_duration_ms=706, response_status=404, connection=1, protocol="h2", domain_lookup_duration_ms=53, connect_duration_ms=259, secure_connection_duration_ms=137, private_relay=false, request_start_ms=425, request_duration_ms=0, response_start_ms=703, response_duration_ms=2, request_bytes=160, response_bytes=1072, cache_hit=true}`

**Comment by eseiker** [comment]
I experienced the same issue while using Cloudflare WARP. Works fine without it.
Seems GitHub API reaches rate limit frequently with Cloudflare IP...
