### ISSUE TITLE
macOS 13.4 support

### ISSUE THREAD

**Issue by Frityet** [IsaacMarovitz/Whisky#29]
game-porting-toolkit works flawlessly on macOS 13.3, just requiring the "Command line tools for XCode 15 beta". Whilst working on my pull request (#13), I backported it to macOS 13 to work on my machine, with the only change being the closure arguments for a SwiftUI view. Should I make a PR to introduce this change?

**Comment by Frityet** [comment]
the error btw
`/Users/frityet/Documents/Packages/Whisky/Whisky/Views/AppDBView.swift:20:33 Contextual closure type '(String) -> Void' expects 1 argument, but 2 were used in closure body`

Fixed by

```swift
.onChange(of: search) { _, newValue  in
```

to

```
.onChange(of: search) { newValue  in
```

Which seems to still be present in the latest macOS

**Comment by DaveFlashNL** [comment]
whisky app itself will not run on ventura
