### ISSUE TITLE
[Bug]: Bottles are not remembered nor can be imported

### ISSUE THREAD

**Issue by Madoc439** [IsaacMarovitz/Whisky#297]
### Description

If I create a new bottle or import a bottle there are no bottles listed

### Steps to reproduce

Import or create bottle

### Expected behaviour

Bottles will be listed on the left pane

### Logs

```bash
Whisky Version: 1.1.0
Date: 8/9/2023, 9:55:05 AM
macOS Version: Version 14.0 (Build 23A5301h)
Arguments: --version 

Launched Wine (52038)
wine-7.7
Process exited with code 0

Whisky Version: 1.1.0
Date: 8/9/2023, 9:54:53 AM
macOS Version: Version 14.0 (Build 23A5301h)
Bottle Name: Win10
Wine Version: 7.7.0
Wine Binary Version: 5
Windows Version: win10
Bottle URL: /Users/wfj5444 /Bottle/64563ABB-E196-48FA-B0DD-6860FBFF91E0

Arguments: winecfg -v win10 

Launched Wine (51980)
00f0: thread_get_state failed on Apple Silicon - faking zero debug registers
00f8: thread_get_state failed on Apple Silicon - faking zero debug registers
wine: configuration in L"/Users/wfj5444 /Bottle/64563ABB-E196-48FA-B0DD-6860FBFF91E0" has been updated.
Process exited with code 0
```

### What version of Whisky are you using?

1.1.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Mika412** [comment]
Can you confirm that this URL, "/Users/wfj5444 /Bottle/64563ABB-E196-48FA-B0DD-6860FBFF91E0", contains a white space? If yes, then it's a white space bug noted before

**Comment by Madoc439** [comment]
Well I have discovered a fresh Hell.  I have two user folders named wfj5444, the one that actually gets used and I am logged in to now must have a white space in it.  Looking at the log section you copied and pasted you can see it.  

So I will close this bug and ask the question, does anyone know the best way to migrate to a new user/user folder?  I have no idea how this happened.  I would love to take what I have and just change the username and folder name.  Any suggestions?
