### ISSUE TITLE
Performance on league of legends

### ISSUE THREAD

**Issue by KaiLv69** [IsaacMarovitz/Whisky#35]
Any test on league of lengends (Mainland China)? Is it possible to play it on Mac?

**Comment by Wizjonero** [comment]
There's a MacOS version of LoL, why would you want to run it through an emulator?

**Comment by KaiLv69** [comment]
China mainland can't play that. There is only windows version here. ;(

**Comment by IsaacMarovitz** [comment]
GitHub issue isn't the place for this sort of question
