### ISSUE TITLE
[Bug]: Restricted Screen Resolution Options

### ISSUE THREAD

**Issue by Jepl4r** [IsaacMarovitz/Whisky#37]
Is there any way to activate a retina mode to use the full resolution?

**Comment by aayork** [comment]
Yeah I was curious about dxvk too

**Comment by HongyuS** [comment]
There is no Vulkan support in Apple's build. They disabled it on purpose. So DXVK, which depends on Vulkan, will never work.
You may refer to their source code [here](https://github.com/apple/homebrew-apple/blob/main/Formula/game-porting-toolkit.rb).

**Comment by fluxehub** [comment]
Setting `RetinaMode` to `y` as in [this guide](https://gist.github.com/mcxiaoke/bd0c779a01f21baad787f49e7b330faa) fixed blurry resolutions for me, though I couldn't find an obvious way to change the DPI since there's no direct access to wine commands.

**Comment by IsaacMarovitz** [comment]
This option has been added in the next release
