### ISSUE TITLE
[Bug]: Cannot install msi

### ISSUE THREAD

**Issue by Naozumi520** [IsaacMarovitz/Whisky#39]
As title, I'm not able to select .msi file from finder using the "run..." function.

**Comment by IsaacMarovitz** [comment]
Can't recreate

**Comment by jojodat** [comment]
I think it's not a bug but a feautre request.
He wants to be able to install a msi via run...
For example the Epic Games Launcher is distributed as msi.
here the latest Version: https://launcher-public-service-prod06.ol.epicgames.com/launcher/api/installer/download/EpicGamesLauncherInstaller.msi

**Comment by IsaacMarovitz** [comment]
You can already run MSIs


https://github.com/IsaacMarovitz/Whisky/assets/42140194/be408752-4623-4bd3-92ad-c63a0d934618

**Comment by jojodat** [comment]
Are you sure you aren't using some dev build with some applied pullrequests or so?
As there is one for that.

Cause with latest 0.2.2 you can't even select a .msi in finder when pressing run.... - Only .exe

**Comment by LorenzoMorelli** [comment]
Same, I cannot select msi files as well

**Comment by IsaacMarovitz** [comment]
<img width="644" alt="Screenshot 2023-06-09 at 23 49 21" src="https://github.com/IsaacMarovitz/Whisky/assets/42140194/0dac4df3-d6b8-4271-b491-b9dd727fb5b6">

See [BottleView.swift](https://github.com/IsaacMarovitz/Whisky/blob/main/Whisky/Views/Bottle%20Views/BottleView.swift), MSIs are allowed. There might be some strange circumstances where this type does not exist. In that case, it's possible we can override it in the Info.plist.

**Comment by vinc3m1** [comment]
that `com.microsoft.msi-installer` type only works if you have The Unarchiver installed

**Comment by sid9102** [comment]
> That `com.microsoft.msi-installer` type only works if you have The Unarchiver installed. Uninstalling The Unarchiver reproduces the issue again.

Could you elaborate on this? I have to install The Unarchiver in order for MSI's to work? @IsaacMarovitz I think it would make sense to add this to the readme if this is in fact true.

**Comment by IsaacMarovitz** [comment]
> That `com.microsoft.msi-installer` type only works if you have The Unarchiver installed. Uninstalling The Unarchiver reproduces the issue again.

Ahh, that makes sense. I will fix it in the next version

**Comment by IsaacMarovitz** [comment]
Should be fixed in latest commit
