### ISSUE TITLE
[Feature Request]: Bookmark .exe from a bottle.

### ISSUE THREAD

**Issue by CaioFaSoares** [IsaacMarovitz/Whisky#42]
Add another section on BottleView with buttons to quickly run bookmarked executables.

I'm interested in implementing this, but it's my first time trying to contribute. Should I just fork the project, try to implement, and come back here?

**Comment by IsaacMarovitz** [comment]
Added in the next release

**Comment by tarasis** [comment]
How do you do this? I am playing Baldur's Gate 3, and the only exes it has added shortcuts for are the Launcher (which doesn't work), and uninstall. In the programs section it doesn't show either of the bg3 exes. (bg3.exe & bg3_dx11.exe)

So every time I have to hit run, navigate to the folder and click on the exe to run the game.

**Comment by Alex0007** [comment]
@IsaacMarovitz if application is not listed in programs, it's impossible to pin it
