### ISSUE TITLE
[Feature]: Sign Whisky so it can be added to brew or make a brew tap

### ISSUE THREAD

**Issue by benwaco** [IsaacMarovitz/Whisky#51]
### Is your feature request related to a problem?

Whisky is unsigned

### Describe the solution you'd like

Sign Whisky or make a new brew tap

### Anything else?

https://github.com/Homebrew/homebrew-cask/pull/148839

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Signing added

**Comment by benwaco** [comment]
> Signing added

pre-0.2.2 is not signed

**Comment by IsaacMarovitz** [comment]
> pre-0.2.2 is not signed
<img width="610" alt="Screenshot 2023-06-10 at 01 12 35" src="https://github.com/IsaacMarovitz/Whisky/assets/42140194/1db652bd-5c38-4604-8e1b-6cbc22cad105">

It should be

**Comment by IsaacMarovitz** [comment]
If what they want is Notarization, I can't do that right now, I quickly ran into problems running Wine processes from a hardnered runtime

**Comment by benwaco** [comment]
> If what they want is Notarization, I can't do that right now, I quickly ran into problems running Wine processes from a hardened runtime

Oh okay, do you need a developer account to sign it? If so I can help with that if you’re interested.

**Comment by IsaacMarovitz** [comment]
> Oh okay, do you need a developer account to sign it? If so I can help with that if you’re interested.

I renewed my developer account today and tried to make a notarized build. The problem is hardened runtime requires that I sign the wine dylibs, and doing that caused them to outright stop working properly until I figure that out, I unfortunately can't enable hardened runtime, and therefore can't notarise Whisky.

**Comment by IsaacMarovitz** [comment]
I do plan to move the LIbrary folder entirely to Application Support soon-ish, which may be a way to resolve the issue sort of

**Comment by benwaco** [comment]
> > Oh okay, do you need a developer account to sign it? If so I can help with that if you’re interested.
> 
> 
> 
> I renewed my developer account today and tried to make a notarized build. The problem is hardened runtime requires that I sign the wine dylibs, and doing that caused them to outright stop working properly until I figure that out, I unfortunately can't enable hardened runtime, and therefore can't notarise Whisky. 

Oh okay that makes sense, you could maybe [create a brew tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) as an alternative if you want.

**Comment by IsaacMarovitz** [comment]
> Oh okay that makes sense, you could maybe [create a brew tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) as an alternative if you want.

I could yeah, I'll think about it
