### ISSUE TITLE
[Feature]: Allow us to use an existing bottle

### ISSUE THREAD

**Issue by vesper8** [IsaacMarovitz/Whisky#53]
### Is your feature request related to a problem?

I just tried Whisky for the first time on Sonoma after already configuring a bottle via WINEPREFIX and installing a bunch of games and copying my save games from an older CrossOver bottle.

The first thing Whisky wants to help me do is create a new bottle but that's not what I want since I already have one that I'm happy with.

Is there an ini file I can edit somewhere to add an existing bottle?

### Describe the solution you'd like

See above

### Anything else?

See above

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Added
