### ISSUE TITLE
[Bug]: wineboot error

### ISSUE THREAD

**Issue by kvn1351** [IsaacMarovitz/Whisky#56]
### Description

ProductName:		macOS
ProductVersion:		13.3.1
SoC:                                  M1
Whisky ver: Pre-release 0.2.2

Log after creating a bottle
```
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
wine: failed to start L"C:\\windows\\system32\\wineboot.exe"
0024:err:environ:run_wineboot failed to start wineboot c000000d
wine: failed to load start.exe: c000000d
```

Error message when trying to run something:
```
Failed to open program! (Title)
Failed to open XXX.exe: The operation couldn’t be completed. (Swift.String error 1.)
```

### Steps to reproduce

1. Run terminal commands from the Readme
2. Install Whisky
3. Merge lib folder from Apple's Porting Kit
4. Open Whisky
5. Create a bottle

The bottle doesn't show up until I close and reopen the window. I also can't run anything.

### Expected behaviour

It should create a bottle and run executables.

### What version of Whisky are you using?

pre-0.2.2

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by kvn1351** [comment]
I've upgraded to 13.4 and the issue persists.

**Comment by efossvold** [comment]
I'm experiencing the same issue. Also using pre-0.2.2 on MacOS 13.4.

**Comment by JustAcho** [comment]
Yup, same thing on my end - MBP M1 Pro, pre-0.2.2 on MacOS 13.4

**Comment by jipiboily** [comment]
Just FYI (no pressure; thanks for all the work! ❤️ ), I'm still getting that with the new 0.2.2 (second release) on the latest Ventura version on M1 Max.

**Comment by kvn1351** [comment]
Persists on 0.2.3, not that the changelog would suggest otherwise.

**Comment by larryisthere** [comment]
I also get this error:
Failed to open Battle.net-Setup.exe: The operation couldn’t be completed. (Swift.String error 1.)
Mac OSX: Sonoma Beta
Mac: Macbook Pro 32G M2 Max
Whisky: pre-0.3.1 (14)
