### ISSUE TITLE
[Bug]: “Whisky” is damaged and can’t be opened. You should move it to the Trash.  (on Ventura)

### ISSUE THREAD

**Issue by jipiboily** [IsaacMarovitz/Whisky#57]
### Description

Trying to run the latest pre-0.2.2 (_note: impossible to select that version in the new issue screen_) on Ventura (`13.4 (22F66)`), and I'm getting this error:

> “Whisky” is damaged and can’t be opened. You should move it to the Trash.  (on Ventura)

Additional context: I tried installing Game Porting Kit yesterday and ran into some errors while trying to install it through brew (with `brew -v install apple/apple/game-porting-toolkit`, through Roseta + `arch -x86_64 /bin/zsh`). No idea if it could be part of the reason, but I wanted to mention it.

The solution (running `xattr -d com.apple.quarantine <path-to-app> `) suggested in #21 didn't work for me.

### Steps to reproduce

- Download
- Extract the zip file
- Move to `/Applications/Whisky.app`
- Try to open the app
- 💥 

### Expected behaviour

Opening the app without an error

### What version of Whisky are you using?

pre-0.2.1

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
Should be fixed in pre-0.2.2

**Comment by jipiboily** [comment]
I just confirmed that this is solved. Thanks so much!
