### ISSUE TITLE
[Bug]: DirectX 12 games no longer launching on 0.2.2

### ISSUE THREAD

**Issue by breakgimme** [IsaacMarovitz/Whisky#64]
### Description

The title is self-explanatory, DirectX games briefly launch and then quickly turn off without any window showing.

### Steps to reproduce

1.  Launch Whisky 0.2.2
2. Drag the GPTK dmg to the app
3. Try to run any DirectX 12 game

### Expected behaviour

Game launches and works, just like in 0.2.1

### What version of Whisky are you using?

pre-0.2.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by breakgimme** [comment]
still broken as of pre-0.2.3

**Comment by JamIsJam88** [comment]
Does 0.2.1 work?

**Comment by Parsifal09** [comment]
yes, same here. pre-0.2.3 doesn't work for DX12 games.

**Comment by breakgimme** [comment]
> Does 0.2.1 work?

works for me

**Comment by IsaacMarovitz** [comment]
Should be fixed in pre-0.3.0
