### ISSUE TITLE
[Feature]: Compile GPT with SDL and Vulkan Support

### ISSUE THREAD

**Issue by IsaacMarovitz** [IsaacMarovitz/Whisky#74]
### Is your feature request related to a problem?

Controllers and Vulkan games currently do not work

### Describe the solution you'd like

Edit the brew formula and enable Vulkan and SDL

### Anything else?

Nope

### Issue Language

- [X] Yes my issue is written in English

**Comment by DarthMDev** [comment]
Is the plan to have this bundled, I ran into issues myself manually editing it to have vulkan and sdl, it made steam stop working

**Comment by Gcenx** [comment]
The formula already builds against SDL2, my own Xbox One controller works fine in the stock build. Steam could be causing a conflict if the games are being launched via Steam.

**Comment by IsaacMarovitz** [comment]
Coming in next release
