### ISSUE TITLE
[Feature]: Add Winetricks in the configuration menu

### ISSUE THREAD

**Issue by ermaolaoye** [IsaacMarovitz/Whisky#84]
### Is your feature request related to a problem?

A lot of games or game launcher requires different dependencies to work well in wine environments. For example the unofficial XIVLauncher for Final Fantasy XIV requires dot net 4.7.2 to run, which is really troublesome to install in wine.

### Describe the solution you'd like

Winetricks is a convenient tool that efficiently assists users in configuring Windows registries and installing additional DLLs and runtime libraries. Considering the convenience of users, integrating the winetricks binary into the program and adding a button in the configuration menu to access winetricks could potentially alleviate a significant amount of hassle.

### Anything else?

Maybe add a button here?
![image](https://github.com/IsaacMarovitz/Whisky/assets/56563171/0ec69c1a-8c3d-4be0-a16b-b829235bf33d)

### Issue Language

- [X] Yes my issue is written in English

**Comment by kittywhiskers** [comment]
+1

Currently I have a rather inconvenient script to install Core Fonts (see below, adapted from [mybyways](https://mybyways.com/blog/running-steam-in-game-porting-toolkit)), but anything more complicated than that and you start getting major usability issues

```bash
#!/usr/bin/env bash

set -eux

export INSTALL_FONTS=true

export WHISKEY_PASS=false
export WHISKEY_PATH="${HOME}/Library/Application Support/Whisky/Libraries/Wine/bin/"

export WINEESYNC=1
export WINEPREFIX="/Volumes/Storage/Library/Whiskey/Steam"

export ORIGINAL_PATH="$(pwd)"

run_r() {
  echo "Run ${@}"
  cd "${WHISKEY_PATH}"
  ./wine64 "${ORIGINAL_PATH}/${@}" || "${WHISKEY_PASS}"
}

export WHISKEY_PASS=true
# Install fonts
if ${INSTALL_FONTS}; then
  run_r ./fonts/andale32.exe /q
  run_r ./fonts/arial32.exe /q
  run_r ./fonts/arialb32.exe /q
  run_r ./fonts/comic32.exe /q
  run_r ./fonts/courie32.exe /q
  run_r ./fonts/impact32.exe /q
  run_r ./fonts/times32.exe /q
  run_r ./fonts/trebuc32.exe /q
  run_r ./fonts/verdan32.exe /q
  run_r ./fonts/webdin32.exe /q
fi
```

**Comment by mio-19** [comment]
It is possible to run winetricks from comman\d line

```

PATH=~/Library/Application\ Support/Whisky/Libraries/Wine/bin/:$PATH WINEPREFIX=~/Library/Containers/com.isaacmarovitz.Whisky/Bottles/Steam/ WINE=wine64 winetricks
```

**Comment by IsaacMarovitz** [comment]
Winetricks added upstream

**Comment by diericx** [comment]
Worth noting that in order to run winetricks I had to update the command above and do the following. Only relevant until the next build is released.

```bash
$ brew install winetricks zenity
$ PATH=~/Library/Application\ Support/com.isaacmarovitz.Whisky/Libraries/Wine/bin/:$PATH WINEPREFIX=~/Library/Containers/com.isaacmarovitz.Whisky/Bottles/<bottle_id> WINE=wine64 winetricks
```
