### ISSUE TITLE
DXVK not working

### ISSUE THREAD

**Issue by toasterchi** [IsaacMarovitz/Whisky#85]
### Description

Not sure if it is a bug or I'm doing something wrong
Basically says everything in a title. Games that require dx10-11-12 don't work, and DXVK menu is not showing in the config tab
Happens no matter where the application is launched from, both Applications and Downloads folders

<img width="895" alt="image" src="https://github.com/IsaacMarovitz/Whisky/assets/136189042/df34faf1-f436-448e-bbdb-3ac4574454ba">

### Steps to reproduce

Run Whiskey
Drag and drop GPTB when required
Create a bottle
Try to run any game that requires dx10-11-12

### Expected behaviour

Games run normally inside a bottle

### What version of Whisky are you using?

pre-0.2.3

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
GPT does not use DXVK
