### ISSUE TITLE
[Bug]: Wine crashes immediately

### ISSUE THREAD

**Issue by desepticon** [IsaacMarovitz/Whisky#86]
### Description

I'm on macOS Ventura with the latest command line tools beta, and I can't seem to get anything to run at all. It won't run the game, nor will it even run any simple program such as installing vcrun.

SIP is disabled

- preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
- preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
- preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
- preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
- preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
- 0068:err:module:open_builtin_so_file failed to load .so lib "/Applications/Whisky.app/Contents/Resources/Libraries/Wine/lib/wine/x86_64-unix/wineusb.sys.so"
- 0068:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
- preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
- preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
- preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
- preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
- preloader: Warning: failed to reserve range 0000000000010000-0000000000110000

[2023-06-10T18:09:15Z.log](https://github.com/IsaacMarovitz/Whisky/files/11713030/2023-06-10T18.09.15Z.log)

### Steps to reproduce

Created a bottle, which worked fine. Went to try and launch something through it but it won't work.

### Expected behaviour

run the exe

### What version of Whisky are you using?

pre-0.2.3

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by hauntek** [comment]
+1

**Comment by linuzel** [comment]
Same issue here.

**Comment by CaptainGaryPecker** [comment]
same, pls help us

**Comment by alxjzx100** [comment]
Have the same issue, 
Ventura 13.4
Whisky pre-0.2.3 (11)

`preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
0068:err:module:open_builtin_so_file failed to load .so lib "/Applications/Whisky.app/Contents/Resources/Libraries/Wine/lib/wine/x86_64-unix/wineusb.sys.so"
0068:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
00d8: thread_get_state failed on Apple Silicon - faking zero debug registers
`

**Comment by fixmyblock** [comment]
Same issue

OS: Sonoma 14.0
Whisky: pre-0.2.3

* 0068:err:module:open_builtin_so_file failed to load .so lib "/Applications/Whisky.app/Contents/Resources/Libraries/Wine/lib/wine/x86_64-unix/wineusb.sys.so"
* 0068:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142

**Comment by IsaacMarovitz** [comment]
Please don't just reply with "I have the same issue"

**Comment by kevinwright** [comment]
Possibly the same issue. If I look at logs in the `console` App I see all the "failed to reserve range" warnings. And also:

```
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
01e4:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
01e4:err:winediag:nodrv_CreateWindow L"The explorer process failed to start."
```

Nothing is logged to the command line if I launch the app that way.

This is *not* a clean system. I have the beta of both XCode and the command line tools. I previously had the paid version of crossover installed and I tied to install the porting toolkit via the "official" instructions before using Whisky.  I also have a few packages installed under x86 Homebrew and I have Parallels on this machine.

**Comment by kevinwright** [comment]
Results!

I *can* get an application to run if I hit the `wine64` binary directly. So this very much looks to be an issue in the way Whisky is invoking the embedded binary, one that only seems to happen on Ventura.

```
./wine64 ~/Library/Containers/com.isaacmarovitz.Whisky/Bottles/Steam/drive_c/windows/notepad.exe
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
wine: created the configuration directory '/Users/XXXX/.wine'
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
002c:fixme:actctx:parse_depend_manifests Could not find dependent assembly L"Microsoft.Windows.Common-Controls" (6.0.0.0)
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
002c:fixme:shell:create_link failed to connect to mount manager
002c:fixme:shell:create_link failed to connect to mount manager
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
00f0:fixme:module:dlopen_32on64_opengl32 loaded "/Applications/Whisky.app/Contents/Resources/Libraries/Wine/lib/wine/x86_32on64-unix/opengl32.dll.so" early @ 0x6a34f000
00f0: thread_get_state failed on Apple Silicon - faking zero debug registers
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
00f8:fixme:module:dlopen_32on64_opengl32 loaded "/Applications/Whisky.app/Contents/Resources/Libraries/Wine/lib/wine/x86_32on64-unix/opengl32.dll.so" early @ 0x69b4f000
00f8: thread_get_state failed on Apple Silicon - faking zero debug registers
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
0110:err:module:open_builtin_so_file failed to load .so lib "/Applications/Whisky.app/Contents/Resources/Libraries/Wine/lib/wine/x86_64-unix/wineusb.sys.so"
0110:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
002c:err:setupapi:SetupDiInstallDevice Failed to start service L"wineusb" for device L"ROOT\\WINE\\WINEUSB", error 1114.
002c:err:setupapi:SetupDiInstallDevice Failed to control service L"wineusb" for device L"ROOT\\WINE\\WINEUSB", error 1062.
wine: configuration in L"/Users/kevin/.wine" has been updated.
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
0024:fixme:imm:ImeSetActiveContext (0x4783d0, 1): stub
0024:fixme:imm:ImmReleaseContext (000000000001007E, 00000000004783D0): stub
0144:fixme:imm:ImeSetActiveContext (0x47d0b0, 0): stub
0144:fixme:imm:ImmReleaseContext (0000000000040052, 000000000047D0B0): stub
```

**Comment by Piipperi** [comment]
I was able to get Notepad to launch, however, I can't seem to be able to actually run any games.
Getting this notable error in the logs: `Assertion failed: (GFXTHandle && "Failed to dlopen D3DMetal"), function D3DRMDispatch_Init_block_invoke, file shared.mm, line 694.`
I am trying to run a game off an external drive (as I don't have space on my internal one). Using macOS 13.4 (22F66) on Macmini8,1 (2018)

**Comment by Patt92** [comment]
I have the same behaviour. Always present in the logs.
0068:err:module:open_builtin_so_file failed to load .so lib "/Applications/Whisky.app/Contents/Resources/Libraries/Wine/lib/wine/x86_64-unix/wineusb.sys.so"
&
00bc: thread_get_state failed on Apple Silicon - faking zero debug registers

The error with wineusb.sys shouldn't be an issue, because the behaviour is the same, when disabling/deleting the kernel driver in the services.

**Comment by pilisir** [comment]
I fixed it via clearing all related files and folder of old Whisky app first, such as '~/Library/Application Support/Whisky/...'.
And drag new Whisky app to /Applications to restart setps, everything goes fine now.

[AppClear (free)](https://www.macupdate.com/app/mac/25276/appcleaner) provides a simply way to help you.

**Comment by HobbyDev1** [comment]
may be it fits in here even if it is closed already. May System is based on Apple M1 Pro and MacOS 13.4.1
As admin I did the following:
(1) installed XQuartz (-> brew install ––cask xquartz)
(2) installed wine (-> brew install ––cask ––no-quarantine wine-stable)
(3) installed winetricks (-> brew install winetricks)
(4) dowloaded Setup-File (Airstudio -> https://www.jbmedia.eu/light-manager/download/)
(5) opened terminal, cd to the download folder and run "wine64 airstudioSetup.exe"

In the Dock a wine64-preloader pops up and in the terminal I got the following messages:
admin@MacBook-Pro downloads % wine64 airstudioSetup.exe
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
0120:err:environ:init_peb starting L"Z:\\Users\\admin\\downloads\\airstudioSetup.exe" in experimental wow64 mode
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
0128:err:environ:init_peb starting L"C:\\users\\admin\\Temp\\is-OSIJI.tmp\\airstudioSetup.tmp" in experimental wow64 mode
0128:fixme:imm:ImeSetActiveContext (00020068, 1): stub
0128:fixme:imm:ImmReleaseContext (00020064, 00020068): stub
0128:fixme:win:DisableProcessWindowsGhosting : stub
0128:fixme:graphics:ShutdownBlockReasonDestroy (00020064): stub
0128:fixme:graphics:ShutdownBlockReasonCreate (00020064, L"Installiere ..."): stub
0128:fixme:msg:ChangeWindowMessageFilterEx 00010078 c047 1 00000000

Nothing more happens, the terminal as well as the wine64-preloader have to be killed manually.
