### ISSUE TITLE
Diablo 4: you need at least windows 10 version 1909

### ISSUE THREAD

**Issue by obizonit** [IsaacMarovitz/Whisky#93]
### Description

Hey, trying to play D4 using Whisky and always get this message: you need at least windows 10 version 1909. Any workaround pls?

### Steps to reproduce

Try to run D4 through Wisky.

### Expected behaviour

You'll get this message: you need at least windows 10 version 1909

### What version of Whisky are you using?

pre-0.2.3

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Marsgames** [comment]
https://github.com/IsaacMarovitz/Whisky/issues/44#issuecomment-1583325888

**Comment by obizonit** [comment]
how do I run regedit.exe? :D (thanks btw)

**Comment by IsaacMarovitz** [comment]
Duplicate of #18
