### ISSUE TITLE
[Bug]: I installed steam and download games and installed games, nothing run when I run the games

### ISSUE THREAD

**Issue by akaoecia** [IsaacMarovitz/Whisky#94]
### Description

I downloaded pre-0.2.3 and installed steam. nothing run when I run the games which i downloaded from steam. Is there anything I missed? I try run the exe of game directly, nothing work also.

### Steps to reproduce

1.installed command tool for xcode15beta
2.download whisky pre-0.2.3
3.drag game porting toolkit into whisky
4.installed steam 
5.replace account file  of windows steam from mac steam  to login steam
6.install a few games from my steam 
7.not thing work when i click games from steam , same of run game exe directly

### Expected behaviour

run game right and can play

### What version of Whisky are you using?

pre-0.2.3

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by akaoecia** [comment]
or how can i watch the error log?

**Comment by Parsifal09** [comment]
same here. downloaded the games, and ran them, some of them (Chivalry 2) have an icon on the dock but nothing seems to be running, and some (Cyberpunk 2077) just had nothing.

**Comment by aske-cph** [comment]
Same here. On Sonoma.

Tried a wide assortment; Witcher 3, System Shock 2, The Ascent, Mass Effect 3. 

Nothing works through Steam, it just says "running" for a bit then stops. No windows, or errors popup.

**Comment by Lamb1d** [comment]
I have the same issue with the battle.net launcher. The launcher runs as it should, but the games load for 3 seconds after pressing play and then nothing happens.

**Comment by eduardo-pellenz** [comment]
Same here

**Comment by hauntek** [comment]
I feel that Whiskey does not support running games, why I have tried more than 30 games, but there is no response at all? Only the application exe displayed by the GUI can run? Can't all programs of d3d graphics run?

**Comment by RobertMeow** [comment]
same here

**Comment by RobertMeow** [comment]
I deleted ALL the bottles, did everything in order according to the guide https://www.applegamingwiki.com/wiki/Game_Porting_Toolkit and it all worked (I ran cyberpunk)! it didn’t work with Whisky, maybe it would work with Whisky after reinstallation, but I haven’t tried it...

I have beta sonoma, MacBook 14 Pro 2021 (M1 Pro, 16GB)

**Comment by ohaiibuzzle** [comment]
We squashed a buttload of Wine bugs in 0.3.0. Perhaps you want to check that

**Comment by richstokes** [comment]
Same here, games just instantly died. On 0.3.0, too

**Comment by IsaacMarovitz** [comment]
This issue is too broad IMO. Please open specific issues on a game-by-game basis
