### ISSUE TITLE
[Bug]: DirectX runtime installer (9.0c) can't doing install 

### ISSUE THREAD

**Issue by 97lily** [IsaacMarovitz/Whisky#96]
### Description

This is a partial report, but when I tried to install the DrectX runtime, which is required when installing the game, it was not working properly due to an error.

### Steps to reproduce

1. Download directX installer from offician download center https://www.microsoft.com/en-us/download/details.aspx?id=8109
2. You will be asked for the extraction destination, so expand it to a safe location (in this case, c:\dxtemp was specified as the installer's extraction destination)
3. The installer "by itself" runs fine, but fails during the runtime installation stage with an error.

note:The log data is long so I uploaded it as a file for visibility
[DirectX.log](https://github.com/IsaacMarovitz/Whisky/files/11719238/DirectX.log)

### Expected behaviour

Originally, the runtime required to operate the Touhou series and Teamfortless2 should have been installed.

### What version of Whisky are you using?

pre-0.2.3

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by IsaacMarovitz** [comment]
DX9 support added in 1.0.0
