### ISSUE TITLE
[Bug]: Nothing happened when I open Genshin.exe or Honkai: Star Rail.exe

### ISSUE THREAD

**Issue by ErBWs** [IsaacMarovitz/Whisky#98]
### Description

As what I said above, but SteamSetup.exe is running very well.

### Steps to reproduce

Create a Windows10 bottle and click `Run...` to open Genshin.exe or Honkai: Star Rail.exe

### Expected behaviour

It should display the launcher.

### What version of Whisky are you using?

pre-0.2.3

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by hauntek** [comment]
I also encountered this situation. I opened Genshin.exe with Game Porting Toolkit and everything was fine, but there was nothing when I opened Genshin.exe with Whiskey. I wonder if Whiskey uses the Game Porting Toolkit lib? If the Game Porting Toolkit is used, why can the Game Porting Toolkit open Genshin.exe, but Whiskey cannot open Genshin.exe?

**Comment by IsaacMarovitz** [comment]
<img width="1300" alt="Screenshot 2023-07-02 at 11 58 28" src="https://github.com/IsaacMarovitz/Whisky/assets/42140194/7ff48262-63bc-418d-9161-a78819b7ae83">
Launcher works fine for me on latest Whisky

**Comment by gaetschwartz** [comment]
Launcher and installation works fine but when you press launch it never opens the actual game iirc

**Comment by IsaacMarovitz** [comment]
<img width="1440" alt="Screenshot 2023-07-23 at 16 36 47" src="https://github.com/IsaacMarovitz/Whisky/assets/42140194/ed42d9a2-6b82-4fa3-8929-078b235cd107">
Can confirm, with the appropriate workarounds the game works.

**Comment by gaetschwartz** [comment]
oh wow, could you point me to the aforementioned workarounds ?

**Comment by IsaacMarovitz** [comment]
> oh wow, could you point me to the aforementioned workarounds ?

Unfortunately I cannot. Some diligent googling will find it.

**Comment by zackhsuan** [comment]
> oh wow, could you point me to the aforementioned workarounds ?

hey man, did you manage to get the workaround? much appreciated!

**Comment by GalaxySciTech** [comment]
i met same issue
